import Foundation

/// JSON-serializable workout summary for export.
struct WorkoutExportSummary: Codable {
    let appName: String
    let exportVersion: String
    let exportDate: Date
    let privacyNote: String

    let workoutTitle: String
    let source: String
    let startDate: Date?
    let endDate: Date?
    let routePointCount: Int

    let totalDistanceMeters: Double
    let totalDurationSeconds: Double
    let averagePaceSecondsPerKilometer: Double
    let averageSpeedMetersPerSecond: Double

    let elevationGainMeters: Double
    let elevationLossMeters: Double

    let averageHeartRateBPM: Double?
    let maxHeartRateBPM: Double?

    let splits: [SplitExport]
    let segments: [SegmentExport]

    init(workout: RunWorkout, segments: [SegmentHighlight]) {
        self.appName = "RunPlay Studio"
        self.exportVersion = "1.0"
        self.exportDate = Date()
        self.privacyNote = "Local export generated by RunPlay Studio. No data was uploaded to any server."

        self.workoutTitle = workout.displayName
        self.source = workout.source.rawValue
        self.startDate = workout.metadata.startDate
        self.endDate = workout.metadata.endDate
        self.routePointCount = workout.routePoints.count

        self.totalDistanceMeters = workout.summary.totalDistanceMeters
        self.totalDurationSeconds = workout.summary.totalElapsedSeconds
        self.averagePaceSecondsPerKilometer = workout.summary.averagePaceSecondsPerKilometer
        self.averageSpeedMetersPerSecond = workout.summary.averageSpeedMetersPerSecond

        self.elevationGainMeters = workout.summary.elevationGainMeters
        self.elevationLossMeters = workout.summary.elevationLossMeters

        self.averageHeartRateBPM = workout.summary.averageHeartRateBPM
        self.maxHeartRateBPM = workout.summary.maxHeartRateBPM

        self.splits = workout.splits.map { SplitExport(split: $0) }
        self.segments = segments.map { SegmentExport(segment: $0) }
    }
}

/// Exportable split data.
struct SplitExport: Codable {
    let splitIndex: Int
    let startDistanceKm: Double
    let endDistanceKm: Double
    let distanceKm: Double
    let durationSeconds: Double
    let paceSecondsPerKilometer: Double
    let elevationGainMeters: Double?
    let averageHeartRateBPM: Double?

    init(split: RunSplit) {
        self.splitIndex = split.splitIndex
        self.startDistanceKm = split.startDistanceMeters / 1000
        self.endDistanceKm = split.endDistanceMeters / 1000
        self.distanceKm = split.distanceMeters / 1000
        self.durationSeconds = split.elapsedSeconds
        self.paceSecondsPerKilometer = split.paceSecondsPerKilometer
        self.elevationGainMeters = split.elevationGainMeters
        self.averageHeartRateBPM = split.averageHeartRateBPM
    }
}

/// Exportable segment highlight data.
struct SegmentExport: Codable {
    let type: String
    let title: String
    let description: String
    let startDistanceKm: Double
    let endDistanceKm: Double
    let distanceKm: Double
    let startElapsedSeconds: Double
    let endElapsedSeconds: Double
    let durationSeconds: Double
    let paceSecondsPerKilometer: Double?
    let elevationDeltaMeters: Double?
    let averageHeartRateBPM: Double?

    init(segment: SegmentHighlight) {
        self.type = segment.type.rawValue
        self.title = segment.title
        self.description = segment.subtitle
        self.startDistanceKm = segment.startDistanceMeters / 1000
        self.endDistanceKm = segment.endDistanceMeters / 1000
        self.distanceKm = segment.distanceMeters / 1000
        self.startElapsedSeconds = segment.startElapsedSeconds
        self.endElapsedSeconds = segment.endElapsedSeconds
        self.durationSeconds = segment.durationSeconds
        self.paceSecondsPerKilometer = segment.paceSecondsPerKilometer
        self.elevationDeltaMeters = segment.elevationDeltaMeters
        self.averageHeartRateBPM = segment.averageHeartRate
    }
}
