import XCTest
import ZIPFoundation
import RunPlayCore
@testable import RunPlayPlatform

/// Reading a synthetic `export.zip` into a scan and candidates.
///
/// Every archive here is built in a temporary directory from generated bytes;
/// nothing is read from disk on the developer's machine.
final class AppleHealthArchiveServiceTests: XCTestCase {

    private var tempDir: URL!

    override func setUp() {
        super.setUp()
        tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("AppleHealthArchive-\(UUID().uuidString)")
        try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    }

    override func tearDown() {
        try? FileManager.default.removeItem(at: tempDir)
        super.tearDown()
    }

    // MARK: - Synthetic fixtures

    private func writeZip(named: String, entries: [(path: String, data: Data)]) throws -> URL {
        let url = tempDir.appendingPathComponent(named)
        if FileManager.default.fileExists(atPath: url.path) {
            try FileManager.default.removeItem(at: url)
        }
        let archive = try Archive(url: url, accessMode: .create)
        for entry in entries {
            try archive.addEntry(
                with: entry.path,
                type: .file,
                uncompressedSize: Int64(entry.data.count),
                provider: { position, size in
                    let start = Int(position)
                    let end = min(start + size, entry.data.count)
                    return entry.data.subdata(in: start..<end)
                }
            )
        }
        return url
    }

    private func healthDocument(records: String = "", workouts: String = "") -> Data {
        let xml = """
        <?xml version="1.0" encoding="UTF-8"?>
        <HealthData locale="en_US">
        \(records)
        \(workouts)
        </HealthData>
        """
        return Data(xml.utf8)
    }

    private func runningWorkout(
        _ start: String = "2026-09-01 08:00:00 +0000",
        _ end: String = "2026-09-01 09:00:00 +0000",
        route: String? = nil
    ) -> String {
        let body = route.map { "<WorkoutRoute><FileReference path=\"\($0)\"/></WorkoutRoute>" } ?? ""
        return "<Workout workoutActivityType=\"HKWorkoutActivityTypeRunning\" "
            + "startDate=\"\(start)\" endDate=\"\(end)\">\(body)</Workout>"
    }

    private func routeGPX() -> Data {
        Data("""
        <?xml version="1.0" encoding="UTF-8"?>
        <gpx version="1.1" creator="RunPlayTest"><trk><trkseg>
        <trkpt lat="37.77" lon="-122.42"><ele>10</ele></trkpt>
        <trkpt lat="37.78" lon="-122.42"><ele>12</ele></trkpt>
        </trkseg></trk></gpx>
        """.utf8)
    }

    private static let exportPath = "apple_health_export/export.xml"
    private static let routePath = "apple_health_export/workout-routes/route_1.gpx"

    // MARK: - Helpers

    private func assertThrows(
        _ expected: AppleHealthArchiveError,
        file: StaticString = #filePath,
        line: UInt = #line,
        _ operation: () async throws -> Void
    ) async {
        do {
            try await operation()
            XCTFail("expected \(expected)", file: file, line: line)
        } catch let error as AppleHealthArchiveError {
            XCTAssertEqual(error, expected, file: file, line: line)
        } catch {
            XCTFail("expected \(expected), got \(error)", file: file, line: line)
        }
    }

    private func assertCancels(
        file: StaticString = #filePath,
        line: UInt = #line,
        _ operation: () async throws -> Void
    ) async {
        do {
            try await operation()
            XCTFail("expected CancellationError", file: file, line: line)
        } catch is CancellationError {
            // expected
        } catch {
            XCTFail("expected CancellationError, got \(error)", file: file, line: line)
        }
    }

    /// Names of the temporary files this service creates and must remove.
    private func leftoverTemporaryFiles() -> [String] {
        let names = (try? FileManager.default.contentsOfDirectory(
            atPath: FileManager.default.temporaryDirectory.path
        )) ?? []
        return names.filter { $0.hasPrefix("runplay-health-") }
    }

    // MARK: - The happy path

    func testSyntheticExportIsScannedIntoCandidates() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout(route: "/workout-routes/route_1.gpx"))),
            (Self.routePath, routeGPX()),
        ])

        let result = try await AppleHealthArchiveService().scan(archiveAt: url)

        XCTAssertEqual(result.exportXMLEntryPath, Self.exportPath)
        XCTAssertFalse(result.usedCaseInsensitiveXMLLookup)
        XCTAssertEqual(result.entryCount, 2)
        XCTAssertEqual(result.routeEntryCount, 1)
        XCTAssertEqual(result.unmatchedRouteReferenceCount, 0)
        XCTAssertGreaterThan(result.uncompressedXMLBytes, 0)

        XCTAssertEqual(result.scan.workouts.count, 1)
        XCTAssertEqual(result.candidates.count, 1)
        let candidate = try XCTUnwrap(result.candidates.first)
        XCTAssertEqual(candidate.routeArchivePath, Self.routePath)
        XCTAssertTrue(candidate.hasRoute)
        XCTAssertEqual(candidate.distanceProvenance, .gpsDerived)
        XCTAssertEqual(candidate.status, .ready)
    }

    func testRouteLessWorkoutCarriesNoRouteAndReportsSourceDistance() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])

        let result = try await AppleHealthArchiveService().scan(archiveAt: url)

        let candidate = try XCTUnwrap(result.candidates.first)
        XCTAssertNil(candidate.routeArchivePath)
        XCTAssertFalse(candidate.hasRoute)
        XCTAssertEqual(candidate.distanceProvenance, .sourceReported)
        XCTAssertEqual(result.routeEntryCount, 0)
    }

    /// A referenced route the archive does not hold is counted, not resolved away.
    func testRouteReferenceWithNoMatchingEntryIsCounted() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout(route: "/workout-routes/route_1.gpx"))),
        ])

        let result = try await AppleHealthArchiveService().scan(archiveAt: url)

        XCTAssertEqual(result.routeEntryCount, 0)
        XCTAssertEqual(result.unmatchedRouteReferenceCount, 1)
    }

    func testHeartRateInsideTheWindowReachesTheCandidate() async throws {
        let record = "<Record type=\"HKQuantityTypeIdentifierHeartRate\" value=\"152\" "
            + "startDate=\"2026-09-01 08:30:00 +0000\" endDate=\"2026-09-01 08:30:00 +0000\"/>"
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(records: record, workouts: runningWorkout())),
        ])

        let result = try await AppleHealthArchiveService().scan(archiveAt: url)

        let candidate = try XCTUnwrap(result.candidates.first)
        XCTAssertEqual(candidate.heartRate.map(\.beatsPerMinute), [152])
    }

    /// Duplicate flagging reaches the candidates without a second heart-rate path.
    func testOverlappingWorkoutsAreFlaggedAsPossibleDuplicates() async throws {
        let first = runningWorkout("2026-09-01 08:00:00 +0000", "2026-09-01 09:00:00 +0000")
        let second = runningWorkout("2026-09-01 08:30:00 +0000", "2026-09-01 09:30:00 +0000")
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: first + second)),
        ])

        let result = try await AppleHealthArchiveService().scan(archiveAt: url)

        XCTAssertEqual(result.candidates.map(\.status), [.possibleDuplicate, .possibleDuplicate])
        XCTAssertTrue(result.candidates.allSatisfy { !$0.isSelectedByDefault })
    }

    /// Whole seconds since the epoch for a UTC instant, computed independently of
    /// the parser's own date handling.
    private func utcSeconds(
        _ year: Int, _ month: Int, _ day: Int, _ hour: Int, _ minute: Int = 0
    ) -> Int64 {
        var components = DateComponents()
        components.year = year
        components.month = month
        components.day = day
        components.hour = hour
        components.minute = minute
        components.timeZone = TimeZone(secondsFromGMT: 0)
        guard let date = Calendar(identifier: .gregorian).date(from: components) else {
            XCTFail("could not build a UTC date for \(year)-\(month)-\(day) \(hour):\(minute)")
            return 0
        }
        return Int64(date.timeIntervalSince1970)
    }

    func testExistingLibraryRunFlagsTheCandidateItOverlaps() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])
        // The workout runs 2026-09-01 08:00:00–09:00:00 UTC.
        let start = utcSeconds(2026, 9, 1, 8)
        let library = [AppleHealthLibraryRunWindow(startSeconds: start, endSeconds: start + 3_600)]

        let result = try await AppleHealthArchiveService().scan(
            archiveAt: url,
            existingLibraryRuns: library
        )

        XCTAssertEqual(result.candidates.map(\.status), [.duplicate])
    }

    // MARK: - Locating the document

    func testArchiveWithoutAnExportDocumentIsRejected() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            ("apple_health_export/readme.txt", Data("no export here".utf8)),
        ])

        await assertThrows(.exportXMLNotFound) {
            _ = try await AppleHealthArchiveService().scan(archiveAt: url)
        }
    }

    func testDocumentFoundByCaseInsensitiveMatchIsReported() async throws {
        let upper = "apple_health_export/EXPORT.XML"
        let url = try writeZip(named: "export.zip", entries: [
            (upper, healthDocument(workouts: runningWorkout())),
        ])

        let result = try await AppleHealthArchiveService().scan(archiveAt: url)

        XCTAssertEqual(result.exportXMLEntryPath, upper)
        XCTAssertTrue(result.usedCaseInsensitiveXMLLookup)
    }

    /// A locale-translated document name is still found: it is the one `.xml`
    /// directly inside the export directory.
    func testTranslatedDocumentNameIsFound() async throws {
        let translated = "apple_health_export/导出.xml"
        let url = try writeZip(named: "export.zip", entries: [
            (translated, healthDocument(workouts: runningWorkout())),
        ])

        let result = try await AppleHealthArchiveService().scan(archiveAt: url)

        XCTAssertEqual(result.exportXMLEntryPath, translated)
        XCTAssertEqual(result.candidates.count, 1)
    }

    /// A traversal name is dropped rather than resolved, so it cannot stand in
    /// for the real document.
    func testTraversalEntryCannotStandInForTheDocument() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            ("../../apple_health_export/export.xml", healthDocument(workouts: runningWorkout())),
        ])

        await assertThrows(.exportXMLNotFound) {
            _ = try await AppleHealthArchiveService().scan(archiveAt: url)
        }
    }

    /// Entries the reader ignores still count toward the archive total.
    func testIgnoredEntriesAreCountedButNotListed() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
            ("apple_health_export/.DS_Store", Data(repeating: 0, count: 32)),
            ("apple_health_export/photos/photo.jpg", Data(repeating: 1, count: 32)),
        ])

        let result = try await AppleHealthArchiveService().scan(archiveAt: url)

        XCTAssertEqual(result.entryCount, 3)
        XCTAssertEqual(result.candidates.count, 1)
    }

    // MARK: - Limits

    func testNonFileURLIsRejected() async throws {
        let remote = try XCTUnwrap(URL(string: "https://example.com/export.zip"))

        await assertThrows(.notALocalFile) {
            _ = try await AppleHealthArchiveService().scan(archiveAt: remote)
        }
    }

    func testArchiveAboveTheFileCapIsRefused() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])
        let service = AppleHealthArchiveService(
            policy: WorkoutArchiveSecurityPolicy(maxArchiveFileBytes: 16)
        )

        await assertThrows(.archiveTooLarge(limitBytes: 16)) {
            _ = try await service.scan(archiveAt: url)
        }
    }

    func testDocumentAboveTheUncompressedCapIsRefused() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])
        let service = AppleHealthArchiveService(
            policy: WorkoutArchiveSecurityPolicy(maxUncompressedEntryBytes: 8)
        )

        await assertThrows(.entryTooLarge(path: Self.exportPath, limitBytes: 8)) {
            _ = try await service.scan(archiveAt: url)
        }
    }

    func testTooManyEntriesIsRefused() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
            (Self.routePath, routeGPX()),
        ])
        let service = AppleHealthArchiveService(
            policy: WorkoutArchiveSecurityPolicy(maxEntryCount: 1)
        )

        await assertThrows(.tooManyEntries(limit: 1)) {
            _ = try await service.scan(archiveAt: url)
        }
    }

    // MARK: - Routes

    func testRouteDataIsReturnedForARoutePath() async throws {
        let gpx = routeGPX()
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout(route: "/workout-routes/route_1.gpx"))),
            (Self.routePath, gpx),
        ])

        let data = try await AppleHealthArchiveService().routeGPXData(
            forArchivePath: Self.routePath,
            archiveAt: url
        )

        XCTAssertEqual(data, gpx)
    }

    func testRouteDataForAnUnknownPathIsRefused() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])

        await assertThrows(.routeEntryNotFound("apple_health_export/workout-routes/missing.gpx")) {
            _ = try await AppleHealthArchiveService().routeGPXData(
                forArchivePath: "apple_health_export/workout-routes/missing.gpx",
                archiveAt: url
            )
        }
    }

    /// The route reader is not a general entry reader: a path outside the route
    /// directory is refused even though the entry exists.
    func testRouteDataOutsideTheRouteDirectoryIsRefused() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])

        await assertThrows(.routeEntryNotFound(Self.exportPath)) {
            _ = try await AppleHealthArchiveService().routeGPXData(
                forArchivePath: Self.exportPath,
                archiveAt: url
            )
        }
    }

    // MARK: - Cancellation

    func testCancellationBeforeTheScanThrowsAndReturnsNothing() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])
        let before = leftoverTemporaryFiles()

        await assertCancels {
            _ = try await AppleHealthArchiveService().scan(
                archiveAt: url,
                isCancelled: { true }
            )
        }
        XCTAssertEqual(leftoverTemporaryFiles(), before)
    }

    /// Cancelling partway through extraction must not leave a half-written
    /// temporary file behind, and must not return a partial scan.
    func testCancellationDuringExtractionLeavesNoTemporaryFile() async throws {
        // Larger than one 64 KiB chunk, so extraction is still running when the
        // predicate first says to stop.
        let filler = String(repeating: "x", count: 200_000)
        let document = healthDocument(
            records: "<!-- \(filler) -->",
            workouts: runningWorkout()
        )
        let url = try writeZip(named: "export.zip", entries: [(Self.exportPath, document)])
        let before = leftoverTemporaryFiles()

        // Calls: 1 is the check after listing, 2 and 3 are the first two
        // extraction chunks. Stopping at 3 cancels mid-extraction.
        let counter = CallCounter(cancelAt: 3)
        await assertCancels {
            _ = try await AppleHealthArchiveService().scan(
                archiveAt: url,
                isCancelled: counter.predicate
            )
        }
        XCTAssertGreaterThanOrEqual(counter.callCount, 3)
        XCTAssertEqual(leftoverTemporaryFiles(), before)
    }

    func testCancellationBeforeRouteReadThrows() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
            (Self.routePath, routeGPX()),
        ])

        await assertCancels {
            _ = try await AppleHealthArchiveService().routeGPXData(
                forArchivePath: Self.routePath,
                archiveAt: url,
                isCancelled: { true }
            )
        }
    }
}

/// A cancellation predicate that counts calls and starts cancelling at a point.
private final class CallCounter: @unchecked Sendable {
    private let lock = NSLock()
    private var calls = 0
    private let cancelAt: Int

    init(cancelAt: Int) {
        self.cancelAt = cancelAt
    }

    var callCount: Int {
        lock.lock()
        defer { lock.unlock() }
        return calls
    }

    var predicate: @Sendable () -> Bool {
        { [self] in
            lock.lock()
            defer { lock.unlock() }
            calls += 1
            return calls >= cancelAt
        }
    }
}
