import XCTest
import ZIPFoundation
import RunPlayCore
@testable import RunPlayPlatform

/// Importing selected Apple Health candidates into the library.
///
/// The archives here are built in a temporary directory from generated bytes.
/// Nothing is read from the developer's machine.
final class AppleHealthImportServiceTests: XCTestCase {

    private var tempDir: URL!

    /// A private extraction root under the test's own directory, so the archive
    /// service never writes into the real app caches directory.
    private var extractionRoot: URL {
        tempDir.appendingPathComponent("extractions", isDirectory: true)
    }

    override func setUp() {
        super.setUp()
        tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("AppleHealthImport-\(UUID().uuidString)")
        try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    }

    override func tearDown() {
        // A test that made the library read-only must not leave it that way, or
        // the recursive delete below fails and the next test starts dirty.
        if let tempDir {
            try? FileManager.default.setAttributes(
                [.posixPermissions: 0o755],
                ofItemAtPath: tempDir.path
            )
        }
        try? FileManager.default.removeItem(at: tempDir)
        super.tearDown()
    }

    // MARK: - Fixtures

    private static let exportPath = "apple_health_export/export.xml"
    private static let routePath = "apple_health_export/workout-routes/route_1.gpx"
    /// The reference a workout record carries. Apple writes it without the
    /// export root and with a leading slash; the scan resolves it to `routePath`.
    private static let routeReference = "/workout-routes/route_1.gpx"

    /// A window both sides agree on, so re-importing compares identically.
    private static let runStart: Int64 = 1_756_650_000
    private static let runEnd: Int64 = 1_756_653_600

    private func makeArchiveService() -> AppleHealthArchiveService {
        AppleHealthArchiveService(
            policy: .default,
            extractionRoot: extractionRoot,
            staleExtractionAge: 3_600,
            availableCapacity: { _ in nil }
        )
    }

    private func makeService() -> AppleHealthImportService {
        AppleHealthImportService(archiveService: makeArchiveService())
    }

    private func makeStore(named name: String) -> (FileWorkoutLibraryStore, WorkoutLibraryStoreActor, URL) {
        let root = tempDir.appendingPathComponent(name)
        let store = FileWorkoutLibraryStore(rootURL: root)
        return (store, WorkoutLibraryStoreActor(store: store), root)
    }

    /// Apple's fixed-width timestamp, which is what the export writes.
    private func appleStamp(_ seconds: Int64) -> String {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        formatter.dateFormat = "yyyy-MM-dd HH:mm:ss Z"
        return formatter.string(from: Date(timeIntervalSince1970: TimeInterval(seconds)))
    }

    private func routeGPX(startSeconds: Int64, points: Int = 3) -> Data {
        func stamp(_ offset: Int) -> String {
            let formatter = ISO8601DateFormatter()
            formatter.timeZone = TimeZone(secondsFromGMT: 0)
            return formatter.string(
                from: Date(timeIntervalSince1970: TimeInterval(startSeconds + Int64(offset)))
            )
        }
        var xml = """
        <?xml version="1.0" encoding="UTF-8"?>
        <gpx version="1.1" creator="RunPlayTest"><trk><trkseg>
        """
        for index in 0..<points {
            let lat = 37.77 + Double(index) * 0.001
            xml += """
            <trkpt lat="\(lat)" lon="-122.42"><ele>\(10 + index)</ele><time>\(stamp(index * 30))</time></trkpt>
            """
        }
        xml += "</trkseg></trk></gpx>"
        return Data(xml.utf8)
    }

    /// One workout record, shaped the way the export writes it.
    ///
    /// `route` is the reference the record carries, or nil for a run with no
    /// route at all — the export's own totals are then its only numbers.
    private func workoutRecord(
        startSeconds: Int64,
        endSeconds: Int64,
        route: String? = nil,
        distanceMeters: Double? = nil
    ) -> String {
        let stats = distanceMeters.map {
            "<WorkoutStatistics type=\"HKQuantityTypeIdentifierDistanceWalkingRunning\" "
                + "startDate=\"\(appleStamp(startSeconds))\" endDate=\"\(appleStamp(endSeconds))\" "
                + "sum=\"\($0)\" unit=\"m\"/>"
        } ?? ""
        let body = route.map { "<WorkoutRoute><FileReference path=\"\($0)\"/></WorkoutRoute>" } ?? ""
        return "<Workout workoutActivityType=\"HKWorkoutActivityTypeRunning\" "
            + "startDate=\"\(appleStamp(startSeconds))\" endDate=\"\(appleStamp(endSeconds))\">"
            + "\(stats)\(body)</Workout>"
    }

    private func heartRateRecord(seconds: Int64, bpm: Int = 150) -> String {
        let stamp = appleStamp(seconds)
        return "<Record type=\"HKQuantityTypeIdentifierHeartRate\" value=\"\(bpm)\" "
            + "startDate=\"\(stamp)\" endDate=\"\(stamp)\"/>"
    }

    private func healthDocument(records: String = "", workouts: String = "") -> Data {
        Data("""
        <?xml version="1.0" encoding="UTF-8"?>
        <HealthData locale="en_US">
        \(records)
        \(workouts)
        </HealthData>
        """.utf8)
    }

    private func writeZip(
        named: String,
        entries: [(path: String, data: Data)]
    ) throws -> URL {
        let url = tempDir.appendingPathComponent(named)
        if FileManager.default.fileExists(atPath: url.path) {
            try FileManager.default.removeItem(at: url)
        }
        let archive = try Archive(url: url, accessMode: .create)
        for entry in entries {
            try archive.addEntry(
                with: entry.path,
                type: .file,
                uncompressedSize: Int64(entry.data.count),
                provider: { position, size in
                    let start = Int(position)
                    let end = min(start + size, entry.data.count)
                    return entry.data.subdata(in: start..<end)
                }
            )
        }
        return url
    }

    /// One routed and one route-less workout, so every path in the service is
    /// exercised by the shared fixture.
    ///
    /// The route-less run's start is far enough from the routed one that the two
    /// windows do not touch, so neither is flagged against the other.
    private func makeMixedArchive(
        named: String = "mixed.zip",
        routedStart: Int64 = AppleHealthImportServiceTests.runStart,
        routeLessStart: Int64 = AppleHealthImportServiceTests.runStart + 7_200
    ) throws -> URL {
        return try writeZip(named: named, entries: [
            (Self.exportPath, healthDocument(
                records: [
                    heartRateRecord(seconds: routedStart + 60, bpm: 142),
                    heartRateRecord(seconds: routeLessStart + 60, bpm: 158),
                ].joined(separator: "\n"),
                workouts: [
                    workoutRecord(
                        startSeconds: routedStart,
                        endSeconds: routedStart + 3_600,
                        route: Self.routeReference
                    ),
                    workoutRecord(
                        startSeconds: routeLessStart,
                        endSeconds: routeLessStart + 1_800,
                        distanceMeters: 3_200
                    ),
                ].joined(separator: "\n")
            )),
            (Self.routePath, routeGPX(startSeconds: routedStart)),
        ])
    }

    private func scan(
        _ url: URL,
        existingLibraryRuns: [AppleHealthLibraryRunWindow] = []
    ) async throws -> AppleHealthArchiveScanResult {
        try await makeArchiveService().scan(
            archiveAt: url,
            existingLibraryRuns: existingLibraryRuns
        )
    }

    /// Every workout the library holds, in manifest order.
    ///
    /// A library that was never written has no manifest, which is the empty
    /// library rather than an error — and is exactly the state an import that
    /// rolled back leaves behind.
    private func libraryWorkouts(_ store: FileWorkoutLibraryStore) throws -> [RunWorkout] {
        do {
            return try store.loadManifest().workoutIDs.map { try store.loadWorkout(id: $0) }
        } catch let error as WorkoutLibraryError {
            if case .manifestMissing = error { return [] }
            throw error
        }
    }

    // MARK: - Route provenance

    func testRoutedCandidateImportsWithGPSDerivedDistance() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        let routed = try XCTUnwrap(result.candidates.first { $0.hasRoute })

        let (store, storeActor, _) = makeStore(named: "lib-routed")
        let report = try await makeService().importSelection(
            [routed],
            from: result,
            archiveAt: zip,
            storeActor: storeActor
        )

        XCTAssertEqual(report.importedCount, 1)
        XCTAssertEqual(report.importedWithoutRouteCount, 0)
        XCTAssertFalse(report.wasCancelled)
        XCTAssertFalse(report.commitFailed)

        let workout = try XCTUnwrap(try libraryWorkouts(store).first)
        XCTAssertEqual(workout.summary.distanceProvenance, .gpsDerived)
        XCTAssertFalse(workout.routePoints.isEmpty, "a routed import must carry its route")
        XCTAssertEqual(workout.source, .healthKit)
        XCTAssertEqual(workout.metadata.recordedUTCOffsetSeconds, 0)
        XCTAssertEqual(workout.importProvenance?.provider, .appleHealthExport)
        XCTAssertEqual(workout.importProvenance?.providerActivityID, routed.id)
        XCTAssertNotNil(workout.importProvenance?.contentSHA256)
    }

    func testRouteLessCandidateImportsAsSourceReportedAndKeepsHeartRate() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        let routeLess = try XCTUnwrap(result.candidates.first { !$0.hasRoute })

        let (store, storeActor, _) = makeStore(named: "lib-routeless")
        let report = try await makeService().importSelection(
            [routeLess],
            from: result,
            archiveAt: zip,
            storeActor: storeActor
        )

        XCTAssertEqual(report.importedCount, 1)

        let workout = try XCTUnwrap(try libraryWorkouts(store).first)
        XCTAssertTrue(workout.routePoints.isEmpty)
        XCTAssertEqual(workout.summary.distanceProvenance, .sourceReported)
        XCTAssertEqual(workout.summary.totalDistanceMeters, 3_200, accuracy: 0.001)
        XCTAssertEqual(workout.summary.totalElapsedSeconds, 1_800, accuracy: 0.001)
        XCTAssertEqual(workout.source, .healthKit)
        XCTAssertNil(workout.importProvenance?.contentSHA256, "a route-less run has no source file to hash")

        // The heart rate the scan joined to this window survives the import.
        let series = try XCTUnwrap(workout.heartRateSeries)
        XCTAssertEqual(series.count, 1)
        XCTAssertEqual(series[0].heartRateBPM, 158)
        XCTAssertEqual(series[0].elapsedSeconds, 60, accuracy: 0.001)
    }

    func testRoutedCandidateWhoseRouteIsAbsentIsImportedWithoutItAndSaysSo() async throws {
        // The workout names a route file the archive does not contain. The scan
        // counts it as an unmatched reference; the import must still bring the
        // run in, and must not pretend it has a route.
        let zip = try writeZip(named: "missing-route.zip", entries: [
            (Self.exportPath, healthDocument(workouts: workoutRecord(
                startSeconds: Self.runStart,
                endSeconds: Self.runStart + 1_800,
                route: "/workout-routes/route_absent.gpx",
                distanceMeters: 4_100
            ))),
        ])

        let result = try await scan(zip)
        XCTAssertEqual(result.report.unmatchedRouteReferenceCount, 1)

        let (store, storeActor, _) = makeStore(named: "lib-missing-route")
        let report = try await makeService().importSelection(
            result.candidates,
            from: result,
            archiveAt: zip,
            storeActor: storeActor
        )

        XCTAssertEqual(report.importedWithoutRouteCount, 1)
        XCTAssertEqual(report.importedCount, 0)
        XCTAssertEqual(report.failedCount, 0)
        let detail = try XCTUnwrap(report.items.first?.detail)
        XCTAssertTrue(
            detail.contains("without its route"),
            "the item must say the route was unavailable, got: \(detail)"
        )

        let workout = try XCTUnwrap(try libraryWorkouts(store).first)
        XCTAssertTrue(workout.routePoints.isEmpty)
        XCTAssertEqual(workout.summary.distanceProvenance, .sourceReported)
    }

    // MARK: - Report counts

    func testReportCarriesTheArchiveLossCountsBesideTheItemOutcomes() async throws {
        // A document the scan cannot build a workout from, plus a workout naming
        // an absent route: one dropped, one unmatched.
        let unreadable = "<Workout workoutActivityType=\"HKWorkoutActivityTypeRunning\" "
            + "startDate=\"not-a-date\" endDate=\"also-not-a-date\"/>"
        let zip = try writeZip(named: "losses.zip", entries: [
            (Self.exportPath, healthDocument(workouts: unreadable + workoutRecord(
                startSeconds: Self.runStart,
                endSeconds: Self.runStart + 1_800,
                route: "/workout-routes/route_absent.gpx",
                distanceMeters: 4_100
            ))),
        ])

        let result = try await scan(zip)
        XCTAssertEqual(result.report.droppedWorkoutCount, 1)
        XCTAssertEqual(result.report.unmatchedRouteReferenceCount, 1)

        let (_, storeActor, _) = makeStore(named: "lib-losses")
        let report = try await makeService().importSelection(
            result.candidates,
            from: result,
            archiveAt: zip,
            storeActor: storeActor
        )

        XCTAssertEqual(report.droppedWorkoutCount, 1)
        XCTAssertEqual(report.unmatchedRouteReferenceCount, 1)
        XCTAssertEqual(report.importedWithoutRouteCount, 1)
    }

    // MARK: - Idempotency

    func testImportingTheSameExportTwiceAddsNothingTheSecondTime() async throws {
        let zip = try makeMixedArchive()
        let (store, storeActor, _) = makeStore(named: "lib-twice")

        // First pass: nothing in the library, so nothing to compare against.
        let first = try await scan(zip)
        let firstReport = try await makeService().importSelection(
            first.candidates,
            from: first,
            archiveAt: zip,
            storeActor: storeActor
        )
        XCTAssertEqual(firstReport.addedWorkoutCount, 2)
        let afterFirst = try libraryWorkouts(store)
        XCTAssertEqual(afterFirst.count, 2)

        // Second pass, over the same archive with the library as it now stands.
        // The candidates are force-selected wholesale, so this cannot pass by
        // the review having unchecked them.
        let second = try await scan(zip)
        let secondReport = try await makeService().importSelection(
            second.candidates,
            from: second,
            archiveAt: zip,
            existingWorkouts: try libraryWorkouts(store),
            storeActor: storeActor
        )

        XCTAssertEqual(secondReport.addedWorkoutCount, 0)
        XCTAssertEqual(secondReport.items.count, 2)
        XCTAssertTrue(
            secondReport.items.allSatisfy { $0.outcome == .alreadyInLibrary },
            "every candidate should be recognised as already imported, got "
                + "\(secondReport.items.map(\.outcome))"
        )
        XCTAssertEqual(secondReport.alreadyInLibraryCount, 2)

        let afterSecond = try libraryWorkouts(store)
        XCTAssertEqual(afterSecond.count, 2)
        XCTAssertEqual(Set(afterSecond.map(\.id)), Set(afterFirst.map(\.id)))
    }

    func testCandidateOverlappingALibraryRunButNotMatchingItIsStillImported() async throws {
        // Idempotency must be exact, not loose: a genuinely different run that
        // merely overlaps one already stored is a run the user did, and skipping
        // it would lose data.
        let zip = try makeMixedArchive()
        let (_, storeActor, _) = makeStore(named: "lib-overlap")

        let overlapping = AppleHealthLibraryRunWindow(
            startSeconds: Self.runStart + 300,
            endSeconds: Self.runEnd + 300
        )
        let result = try await scan(zip, existingLibraryRuns: [overlapping])
        let report = try await makeService().importSelection(
            result.candidates,
            from: result,
            archiveAt: zip,
            existingWorkouts: [Self.libraryRun(startSeconds: Self.runStart + 300, endSeconds: Self.runEnd + 300)],
            storeActor: storeActor
        )

        XCTAssertEqual(report.alreadyInLibraryCount, 0)
        XCTAssertEqual(report.addedWorkoutCount, 2)
    }

    private static func libraryRun(startSeconds: Int64, endSeconds: Int64) -> RunWorkout {
        RunWorkout(
            metadata: WorkoutMetadata(
                startDate: Date(timeIntervalSince1970: TimeInterval(startSeconds)),
                endDate: Date(timeIntervalSince1970: TimeInterval(endSeconds))
            ),
            analysisVersion: RunWorkout.currentAnalysisVersion
        )
    }

    // MARK: - Atomicity

    func testCancellingMidStagingLeavesTheLibraryUnchanged() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        XCTAssertEqual(result.candidates.count, 2)
        let (store, storeActor, _) = makeStore(named: "lib-cancel")

        // Cancel from the first staging progress report, which arrives after one
        // workout has already been handed to the library's staging area. The
        // batch must therefore be rolled back rather than left half-promoted.
        let cancelled = Atomic(false)
        let service = makeService()
        let report = try await service.importSelection(
            result.candidates,
            from: result,
            archiveAt: zip,
            storeActor: storeActor,
            progress: { progress in
                if progress.phase == .staging { cancelled.set(true) }
            },
            isCancelled: { cancelled.value }
        )

        XCTAssertTrue(report.wasCancelled)
        XCTAssertEqual(report.addedWorkoutCount, 0)
        XCTAssertFalse(report.commitFailed)
        // The cancellation landed after the first workout was staged, which is
        // what makes this a test of the rollback rather than of the early exit.
        XCTAssertEqual(report.items.count, 1, "expected to stop after the first candidate staged")
        XCTAssertEqual(report.discardedCount, 1)
        XCTAssertEqual(report.importedCount, 0, "a discarded workout must not be reported as imported")
        XCTAssertTrue(try libraryWorkouts(store).isEmpty, "a cancelled import must add nothing")
        let hasActiveBatch = await storeActor.hasActiveBatch
        XCTAssertFalse(hasActiveBatch, "a cancelled import must release the batch")
    }

    func testFailingMidCommitLeavesTheLibraryUnchanged() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        let (store, storeActor, libraryRoot) = makeStore(named: "lib-commit-fail")

        // Make the library directory read-only at the moment the pass is about to
        // commit. Staging has already succeeded and the promote cannot, which is
        // the failure the batch seam has to survive with the library untouched.
        let service = makeService()
        let report = try await service.importSelection(
            result.candidates,
            from: result,
            archiveAt: zip,
            storeActor: storeActor,
            progress: { progress in
                guard progress.phase == .committing else { return }
                try? FileManager.default.setAttributes(
                    [.posixPermissions: 0o555],
                    ofItemAtPath: libraryRoot.path
                )
            }
        )

        XCTAssertTrue(report.commitFailed, "the commit was expected to fail")
        XCTAssertNotNil(report.errorMessage)
        XCTAssertEqual(report.addedWorkoutCount, 0)
        XCTAssertEqual(report.importedCount, 0, "nothing that was staged may be reported as imported")
        XCTAssertEqual(report.discardedCount, result.candidates.count)
        XCTAssertEqual(report.failedCount, 0, "a rolled-back workout is discarded, not failed")

        // Restore write access before inspecting, then assert the library is as
        // it was: no manifest, no promoted snapshots.
        try? FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: libraryRoot.path
        )
        XCTAssertTrue(try libraryWorkouts(store).isEmpty, "a failed commit must add nothing")
    }

    func testEmptySelectionDoesNotTakeTheLibraryBatch() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        let (_, storeActor, _) = makeStore(named: "lib-empty")

        let report = try await makeService().importSelection(
            [],
            from: result,
            archiveAt: zip,
            storeActor: storeActor
        )

        XCTAssertTrue(report.items.isEmpty)
        XCTAssertEqual(report.addedWorkoutCount, 0)
        // The report still states what the export itself lost.
        XCTAssertEqual(report.droppedWorkoutCount, result.report.droppedWorkoutCount)
        XCTAssertEqual(report.unmatchedRouteReferenceCount, result.report.unmatchedRouteReferenceCount)
        // Nothing was staged, so the batch lock must not have been taken at all.
        let hasActiveBatch = await storeActor.hasActiveBatch
        XCTAssertFalse(hasActiveBatch)
    }

    func testImportRefusesANonLocalArchive() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        let (_, storeActor, _) = makeStore(named: "lib-nonfile")

        let remote = try XCTUnwrap(URL(string: "https://example.com/export.zip"))
        do {
            _ = try await makeService().importSelection(
                result.candidates,
                from: result,
                archiveAt: remote,
                storeActor: storeActor
            )
            XCTFail("expected a non-file archive to be refused")
        } catch let error as AppleHealthImportError {
            XCTAssertEqual(error, .notALocalFile)
        }
    }

    // MARK: - Progress

    func testProgressReportsEveryPhaseAndEndsCompleted() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        let (_, storeActor, _) = makeStore(named: "lib-progress")

        let phases = Atomic<[AppleHealthImportProgress.Phase]>([])
        let totals = Atomic<[Int]>([])
        _ = try await makeService().importSelection(
            result.candidates,
            from: result,
            archiveAt: zip,
            storeActor: storeActor,
            progress: { progress in
                phases.mutate { $0.append(progress.phase) }
                totals.mutate { $0.append(progress.totalCount) }
            }
        )

        XCTAssertEqual(phases.value.first, .importing)
        XCTAssertEqual(phases.value.last, .completed)
        XCTAssertTrue(phases.value.contains(.staging))
        XCTAssertTrue(phases.value.contains(.committing))
        XCTAssertTrue(totals.value.allSatisfy { $0 == 2 })
    }
}

/// A tiny lock-free box the progress closures can write from another task.
///
/// `XCTest` closures here are `@Sendable` and may run on the service's actor, so
/// the test cannot keep the state in a captured `var`.
private final class Atomic<Value>: @unchecked Sendable {
    private let lock = NSLock()
    private var storage: Value

    init(_ value: Value) {
        storage = value
    }

    var value: Value {
        lock.lock()
        defer { lock.unlock() }
        return storage
    }

    func set(_ value: Value) {
        lock.lock()
        storage = value
        lock.unlock()
    }

    func mutate(_ body: (inout Value) -> Void) {
        lock.lock()
        body(&storage)
        lock.unlock()
    }
}
