import XCTest
import ZIPFoundation
import RunPlayCore
@testable import RunPlayPlatform

/// Reading a synthetic `export.zip` into a scan and candidates.
///
/// Every archive here is built in a temporary directory from generated bytes —
/// except the two checked-in `Fixtures/apple-health-zip64-descriptors*.zip`, which
/// are generated from invented content by the script beside them. Both are
/// synthetic: nothing is read from the developer's machine.
final class AppleHealthArchiveServiceTests: XCTestCase {

    private var tempDir: URL!

    /// A private extraction root under the test's own directory, so no test ever
    /// writes into the real app caches directory.
    private var extractionRoot: URL {
        tempDir.appendingPathComponent("extractions", isDirectory: true)
    }

    override func setUp() {
        super.setUp()
        tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("AppleHealthArchive-\(UUID().uuidString)")
        try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    }

    override func tearDown() {
        try? FileManager.default.removeItem(at: tempDir)
        super.tearDown()
    }

    /// A service pointed at the test's private extraction directory.
    ///
    /// `availableCapacity` defaults to `nil`, which disables the free-space
    /// check; a test that exercises it passes a byte count.
    private func makeService(
        policy: WorkoutArchiveSecurityPolicy = .default,
        staleExtractionAge: TimeInterval = 3_600,
        availableCapacity: Int64? = nil,
        sourcePayloadByteLimit: Int64 = Int64(WorkoutImportResourceLimits.maxSourceFileBytes)
    ) -> AppleHealthArchiveService {
        AppleHealthArchiveService(
            policy: policy,
            extractionRoot: extractionRoot,
            staleExtractionAge: staleExtractionAge,
            availableCapacity: { _ in availableCapacity },
            sourcePayloadByteLimit: sourcePayloadByteLimit
        )
    }

    // MARK: - Synthetic fixtures

    private func writeArchive(
        named: String,
        entries: [(path: String, type: Entry.EntryType, data: Data)],
        compression: CompressionMethod = .none
    ) throws -> URL {
        let url = tempDir.appendingPathComponent(named)
        if FileManager.default.fileExists(atPath: url.path) {
            try FileManager.default.removeItem(at: url)
        }
        let archive = try Archive(url: url, accessMode: .create)
        for entry in entries {
            try archive.addEntry(
                with: entry.path,
                type: entry.type,
                uncompressedSize: Int64(entry.data.count),
                compressionMethod: compression,
                provider: { position, size in
                    let start = Int(position)
                    let end = min(start + size, entry.data.count)
                    return entry.data.subdata(in: start..<end)
                }
            )
        }
        return url
    }

    private func writeZip(named: String, entries: [(path: String, data: Data)]) throws -> URL {
        try writeArchive(named: named, entries: entries.map { ($0.path, .file, $0.data) })
    }

    private func healthDocument(records: String = "", workouts: String = "") -> Data {
        let xml = """
        <?xml version="1.0" encoding="UTF-8"?>
        <HealthData locale="en_US">
        \(records)
        \(workouts)
        </HealthData>
        """
        return Data(xml.utf8)
    }

    private func runningWorkout(
        _ start: String = "2026-09-01 08:00:00 +0000",
        _ end: String = "2026-09-01 09:00:00 +0000",
        route: String? = nil
    ) -> String {
        let body = route.map { "<WorkoutRoute><FileReference path=\"\($0)\"/></WorkoutRoute>" } ?? ""
        return "<Workout workoutActivityType=\"HKWorkoutActivityTypeRunning\" "
            + "startDate=\"\(start)\" endDate=\"\(end)\">\(body)</Workout>"
    }

    private func heartRateRecord(value: Int, at instant: String = "2026-09-01 08:30:00 +0000") -> String {
        "<Record type=\"HKQuantityTypeIdentifierHeartRate\" value=\"\(value)\" "
            + "startDate=\"\(instant)\" endDate=\"\(instant)\"/>"
    }

    private func routeGPX() -> Data {
        Data("""
        <?xml version="1.0" encoding="UTF-8"?>
        <gpx version="1.1" creator="RunPlayTest"><trk><trkseg>
        <trkpt lat="37.77" lon="-122.42"><ele>10</ele></trkpt>
        <trkpt lat="37.78" lon="-122.42"><ele>12</ele></trkpt>
        </trkseg></trk></gpx>
        """.utf8)
    }

    private static let exportPath = "apple_health_export/export.xml"
    private static let routePath = "apple_health_export/workout-routes/route_1.gpx"

    // MARK: - Extraction leftovers

    private func extractionFileNames() -> [String] {
        let names = (try? FileManager.default.contentsOfDirectory(atPath: extractionRoot.path)) ?? []
        return names.filter { $0.hasPrefix("runplay-health-extraction-") }.sorted()
    }

    // MARK: - Helpers

    private func assertThrows(
        _ expected: AppleHealthArchiveError,
        file: StaticString = #filePath,
        line: UInt = #line,
        _ operation: () async throws -> Void
    ) async {
        do {
            try await operation()
            XCTFail("expected \(expected)", file: file, line: line)
        } catch let error as AppleHealthArchiveError {
            XCTAssertEqual(error, expected, file: file, line: line)
        } catch {
            XCTFail("expected \(expected), got \(error)", file: file, line: line)
        }
    }

    private func assertFails(
        file: StaticString = #filePath,
        line: UInt = #line,
        _ operation: () async throws -> Void
    ) async {
        do {
            try await operation()
            XCTFail("expected the operation to fail", file: file, line: line)
        } catch {
            // Any error is acceptable here; the caller asserts the residue.
        }
    }

    private func assertCancels(
        file: StaticString = #filePath,
        line: UInt = #line,
        _ operation: () async throws -> Void
    ) async {
        do {
            try await operation()
            XCTFail("expected CancellationError", file: file, line: line)
        } catch is CancellationError {
            // expected
        } catch {
            XCTFail("expected CancellationError, got \(error)", file: file, line: line)
        }
    }

    // MARK: - The happy path

    func testSyntheticExportIsScannedIntoCandidates() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout(route: "/workout-routes/route_1.gpx"))),
            (Self.routePath, routeGPX()),
        ])

        let result = try await makeService().scan(archiveAt: url)

        XCTAssertEqual(result.exportXMLEntryPath, Self.exportPath)
        XCTAssertFalse(result.usedCaseInsensitiveXMLLookup)
        XCTAssertEqual(result.report.entryCount, 2)
        XCTAssertEqual(result.report.routeEntryCount, 1)
        XCTAssertEqual(result.report.unmatchedRouteReferenceCount, 0)
        XCTAssertEqual(result.report.droppedWorkoutCount, 0)
        XCTAssertGreaterThan(result.report.uncompressedXMLBytes, 0)

        XCTAssertEqual(result.scan.workouts.count, 1)
        XCTAssertEqual(result.candidates.count, 1)
        let candidate = try XCTUnwrap(result.candidates.first)
        XCTAssertEqual(candidate.routeArchivePath, Self.routePath)
        XCTAssertTrue(candidate.hasRoute)
        XCTAssertEqual(candidate.distanceProvenance, .gpsDerived)
        XCTAssertEqual(candidate.status, .ready)
    }

    func testRouteLessWorkoutCarriesNoRouteAndReportsSourceDistance() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])

        let result = try await makeService().scan(archiveAt: url)

        let candidate = try XCTUnwrap(result.candidates.first)
        XCTAssertNil(candidate.routeArchivePath)
        XCTAssertFalse(candidate.hasRoute)
        XCTAssertEqual(candidate.distanceProvenance, .sourceReported)
        XCTAssertEqual(result.report.routeEntryCount, 0)
    }

    /// A referenced route the archive does not hold is counted, not resolved away.
    func testRouteReferenceWithNoMatchingEntryIsCounted() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout(route: "/workout-routes/route_1.gpx"))),
        ])

        let result = try await makeService().scan(archiveAt: url)

        XCTAssertEqual(result.report.routeEntryCount, 0)
        XCTAssertEqual(result.report.unmatchedRouteReferenceCount, 1)
    }

    /// The import report carries both loss counts together, which is what a
    /// review screen shows after an import finishes.
    func testReportCarriesDroppedWorkoutsAlongsideUnmatchedRoutes() async throws {
        let unreadable = "<Workout workoutActivityType=\"HKWorkoutActivityTypeRunning\" "
            + "startDate=\"not-a-date\" endDate=\"also-not-a-date\"/>"
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(
                workouts: unreadable + runningWorkout(route: "/workout-routes/missing.gpx")
            )),
        ])

        let result = try await makeService().scan(archiveAt: url)

        XCTAssertEqual(result.report.droppedWorkoutCount, 1)
        XCTAssertEqual(result.report.unmatchedRouteReferenceCount, 1)
        XCTAssertEqual(result.report.candidateCount, 1)
    }

    func testHeartRateInsideTheWindowReachesTheCandidate() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(
                records: heartRateRecord(value: 152),
                workouts: runningWorkout()
            )),
        ])

        let result = try await makeService().scan(archiveAt: url)

        let candidate = try XCTUnwrap(result.candidates.first)
        XCTAssertEqual(candidate.heartRate.map(\.beatsPerMinute), [152])
    }

    /// Duplicate flagging reaches the candidates without a second heart-rate path.
    func testOverlappingWorkoutsAreFlaggedAsPossibleDuplicates() async throws {
        let first = runningWorkout("2026-09-01 08:00:00 +0000", "2026-09-01 09:00:00 +0000")
        let second = runningWorkout("2026-09-01 08:30:00 +0000", "2026-09-01 09:30:00 +0000")
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: first + second)),
        ])

        let result = try await makeService().scan(archiveAt: url)

        XCTAssertEqual(result.candidates.map(\.status), [.possibleDuplicate, .possibleDuplicate])
        XCTAssertTrue(result.candidates.allSatisfy { !$0.isSelectedByDefault })
        XCTAssertEqual(result.report.duplicateCandidateCount, 2)
    }

    /// Whole seconds since the epoch for a UTC instant, computed independently of
    /// the parser's own date handling.
    private func utcSeconds(
        _ year: Int, _ month: Int, _ day: Int, _ hour: Int, _ minute: Int = 0
    ) -> Int64 {
        var components = DateComponents()
        components.year = year
        components.month = month
        components.day = day
        components.hour = hour
        components.minute = minute
        components.timeZone = TimeZone(secondsFromGMT: 0)
        guard let date = Calendar(identifier: .gregorian).date(from: components) else {
            XCTFail("could not build a UTC date for \(year)-\(month)-\(day) \(hour):\(minute)")
            return 0
        }
        return Int64(date.timeIntervalSince1970)
    }

    func testExistingLibraryRunFlagsTheCandidateItOverlaps() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])
        // The workout runs 2026-09-01 08:00:00–09:00:00 UTC.
        let start = utcSeconds(2026, 9, 1, 8)
        let library = [AppleHealthLibraryRunWindow(startSeconds: start, endSeconds: start + 3_600)]

        let result = try await makeService().scan(
            archiveAt: url,
            existingLibraryRuns: library
        )

        XCTAssertEqual(result.candidates.map(\.status), [.duplicate])
    }

    // MARK: - Locating the document

    func testArchiveWithoutAnExportDocumentIsRejected() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            ("apple_health_export/readme.txt", Data("no export here".utf8)),
        ])

        await assertThrows(.exportXMLNotFound) {
            _ = try await makeService().scan(archiveAt: url)
        }
    }

    func testDocumentFoundByCaseInsensitiveMatchIsReported() async throws {
        let upper = "apple_health_export/EXPORT.XML"
        let url = try writeZip(named: "export.zip", entries: [
            (upper, healthDocument(workouts: runningWorkout())),
        ])

        let result = try await makeService().scan(archiveAt: url)

        XCTAssertEqual(result.exportXMLEntryPath, upper)
        XCTAssertTrue(result.usedCaseInsensitiveXMLLookup)
    }

    /// A locale-translated document name is still found: it is the one `.xml`
    /// directly inside the export directory, and its root element says it is a
    /// health export.
    func testTranslatedDocumentNameIsFound() async throws {
        let translated = "apple_health_export/导出.xml"
        let url = try writeZip(named: "export.zip", entries: [
            (translated, healthDocument(workouts: runningWorkout())),
        ])

        let result = try await makeService().scan(archiveAt: url)

        XCTAssertEqual(result.exportXMLEntryPath, translated)
        XCTAssertEqual(result.candidates.count, 1)
    }

    /// More than one candidate document is a refusal, not a guess: the error
    /// names how many were seen so the user can fix the archive.
    func testAmbiguousFallbackDocumentsAreRefusedNamingTheCount() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            ("apple_health_export/first.xml", healthDocument(workouts: runningWorkout())),
            ("apple_health_export/second.xml", healthDocument(workouts: runningWorkout())),
        ])

        await assertThrows(.ambiguousExportXML(candidateCount: 2)) {
            _ = try await makeService().scan(archiveAt: url)
        }
    }

    /// A single unrelated `.xml` in the export directory is not an export, however
    /// lonely it is: its root element has to say `HealthData`.
    func testSingleFallbackDocumentWithAForeignRootIsRefused() async throws {
        let note = "apple_health_export/notes.xml"
        let url = try writeZip(named: "export.zip", entries: [
            (note, Data("<?xml version=\"1.0\"?><Notes><Note>hi</Note></Notes>".utf8)),
        ])

        await assertThrows(.documentIsNotAHealthExport(path: note)) {
            _ = try await makeService().scan(archiveAt: url)
        }
    }

    /// A traversal name is dropped rather than resolved, so it cannot stand in
    /// for the real document.
    func testTraversalEntryCannotStandInForTheDocument() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            ("../../apple_health_export/export.xml", healthDocument(workouts: runningWorkout())),
        ])

        await assertThrows(.exportXMLNotFound) {
            _ = try await makeService().scan(archiveAt: url)
        }
    }

    /// Entries the reader ignores still count toward the archive total.
    func testIgnoredEntriesAreCountedButNotListed() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
            ("apple_health_export/.DS_Store", Data(repeating: 0, count: 32)),
            ("apple_health_export/photos/photo.jpg", Data(repeating: 1, count: 32)),
        ])

        let result = try await makeService().scan(archiveAt: url)

        XCTAssertEqual(result.report.entryCount, 3)
        XCTAssertEqual(result.candidates.count, 1)
    }

    // MARK: - Limits

    func testNonFileURLIsRejected() async throws {
        let remote = try XCTUnwrap(URL(string: "https://example.com/export.zip"))

        await assertThrows(.notALocalFile) {
            _ = try await makeService().scan(archiveAt: remote)
        }
    }

    func testArchiveAboveTheFileCapIsRefused() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])
        let service = makeService(policy: WorkoutArchiveSecurityPolicy(maxArchiveFileBytes: 16))

        await assertThrows(.archiveTooLarge(limitBytes: 16)) {
            _ = try await service.scan(archiveAt: url)
        }
    }

    func testStreamedDocumentAboveInjectedPayloadCapIsAccepted() async throws {
        let document = healthDocument(workouts: runningWorkout())
        let url = try writeZip(named: "export.zip", entries: [(Self.exportPath, document)])
        let service = makeService(
            policy: WorkoutArchiveSecurityPolicy(maxUncompressedEntryBytes: 8),
            sourcePayloadByteLimit: 8
        )
        let result = try await service.scan(archiveAt: url)
        XCTAssertEqual(result.candidateCount, 1)
        XCTAssertEqual(result.report.uncompressedXMLBytes, Int64(document.count))
        XCTAssertTrue(extractionFileNames().isEmpty)
    }

    func testRouteAboveInjectedPayloadCapIsStillRefused() async throws {
        let url = try writeZip(named: "export.zip", entries: [(Self.routePath, routeGPX())])
        await assertThrows(.entryTooLarge(path: Self.routePath, limitBytes: 8)) {
            _ = try await self.makeService(sourcePayloadByteLimit: 8).routeGPXData(
                forArchivePath: Self.routePath, archiveAt: url
            )
        }
    }

    func testTooManyEntriesIsRefused() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
            (Self.routePath, routeGPX()),
        ])
        let service = makeService(policy: WorkoutArchiveSecurityPolicy(maxEntryCount: 1))

        await assertThrows(.tooManyEntries(limit: 1)) {
            _ = try await service.scan(archiveAt: url)
        }
    }

    // MARK: - Extraction hardening

    /// Extraction lands in a private directory this app owns, not the shared
    /// temporary directory, and both directory and file are owner-only.
    func testExtractionUsesAPrivateDirectoryAndOwnerOnlyPermissions() async throws {
        let defaultDirectory = AppleHealthArchiveService.defaultExtractionDirectory()
        XCTAssertTrue(
            defaultDirectory.path.hasSuffix("RunPlayStudio/AppleHealthExtractions"),
            "expected an app-owned subdirectory, got \(defaultDirectory.path)"
        )
        XCTAssertFalse(
            defaultDirectory.path.hasPrefix(FileManager.default.temporaryDirectory.path),
            "extraction must not share the temporary directory root"
        )

        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
            (Self.routePath, routeGPX()),
        ])
        let probe = ExtractionProbe(directory: extractionRoot)

        _ = try await makeService().scan(archiveAt: url, isCancelled: probe.predicate)

        // The file is gone by now, so the mode was captured while it existed.
        XCTAssertEqual(probe.filePermissions, 0o600, "the extraction file must be owner-only")

        let directoryAttributes = try FileManager.default.attributesOfItem(atPath: extractionRoot.path)
        let directoryPermissions = (directoryAttributes[.posixPermissions] as? NSNumber)?.intValue
        XCTAssertEqual(directoryPermissions, 0o700, "the extraction directory must be owner-only")
    }

    /// A parse failure still removes the extracted document.
    func testExtractionFileIsRemovedWhenParsingThrows() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, Data("<HealthData><Workout".utf8)),
        ])

        await assertFails {
            _ = try await makeService().scan(archiveAt: url)
        }
        XCTAssertTrue(extractionFileNames().isEmpty, "a failed parse must leave no extraction file")
    }

    /// The descriptor retains the real size: Entry.uncompressedSize therefore
    /// cannot detect this mismatch. The service must consult the central directory.
    func testUnderstatedCentralDirectorySizeAbortsAndRemovesExtraction() async throws {
        let document = healthDocument(records: "<!-- " + String(repeating: "x", count: 200_000) + " -->")
        let url = try writeArchive(
            named: "understated.zip", entries: [(Self.exportPath, .file, document)], compression: .deflate
        )
        var bytes = try Data(contentsOf: url)
        let central = try XCTUnwrap(bytes.range(of: Data([0x50, 0x4b, 0x01, 0x02]))).lowerBound
        let descriptor = Data([0x50, 0x4b, 0x07, 0x08]) + bytes.subdata(in: (central + 16)..<(central + 28))
        bytes[6] |= 8 // Local header: use a data descriptor.
        bytes.insert(contentsOf: descriptor, at: central)
        let newCentral = central + descriptor.count
        bytes[newCentral + 8] |= 8
        let declared = UInt32(document.count - 1)
        for index in 0..<4 {
            bytes[newCentral + 24 + index] = UInt8(truncatingIfNeeded: declared >> (index * 8))
            bytes[bytes.count - 22 + 16 + index] = UInt8(truncatingIfNeeded: UInt32(newCentral) >> (index * 8))
        }
        try bytes.write(to: url)
        let archive = try Archive(url: url, accessMode: .read)
        XCTAssertEqual(try XCTUnwrap(archive.first { _ in true }).uncompressedSize, UInt64(document.count))
        let probe = ExtractionProbe(directory: extractionRoot)
        await assertThrows(.entryExceedsDeclaredSize(path: Self.exportPath, declaredBytes: UInt64(declared))) {
            _ = try await self.makeService().scan(archiveAt: url, isCancelled: probe.predicate)
        }
        XCTAssertEqual(probe.filePermissions, 0o600, "must abort a real partial extraction")
        XCTAssertTrue(extractionFileNames().isEmpty)
    }

    /// Cancelling partway through extraction removes the half-written file and
    /// returns nothing.
    func testCancellationDuringExtractionLeavesNoExtractionFile() async throws {
        // Larger than one 64 KiB chunk, so extraction is still running when the
        // predicate first says to stop.
        let filler = String(repeating: "x", count: 200_000)
        let document = healthDocument(
            records: "<!-- \(filler) -->",
            workouts: runningWorkout()
        )
        let url = try writeZip(named: "export.zip", entries: [(Self.exportPath, document)])

        // Calls: 1 is the check after listing, 2 and 3 are the first two
        // extraction chunks. Stopping at 3 cancels mid-extraction.
        let counter = CallCounter(cancelAt: 3)
        await assertCancels {
            _ = try await makeService().scan(archiveAt: url, isCancelled: counter.predicate)
        }
        XCTAssertGreaterThanOrEqual(counter.callCount, 3)
        XCTAssertTrue(extractionFileNames().isEmpty)
    }

    /// A crash skips `defer`, so the next import sweeps the orphan it left.
    func testStaleExtractionFileFromAPreviousCrashIsSwept() async throws {
        let staleURL = extractionRoot.appendingPathComponent("runplay-health-extraction-stale.xml")
        try FileManager.default.createDirectory(at: extractionRoot, withIntermediateDirectories: true)
        try Data("<HealthData/>".utf8).write(to: staleURL)
        // Backdate it so it is unambiguously older than the threshold.
        try FileManager.default.setAttributes(
            [.modificationDate: Date().addingTimeInterval(-7_200)],
            ofItemAtPath: staleURL.path
        )

        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])
        _ = try await makeService().scan(archiveAt: url)

        XCTAssertFalse(
            FileManager.default.fileExists(atPath: staleURL.path),
            "a stale extraction file must be swept on the next import"
        )
    }

    /// The sweep is age-gated, so it cannot delete the live file of an import
    /// running in another copy of the app.
    func testFreshExtractionFileIsNotSwept() async throws {
        let freshURL = extractionRoot.appendingPathComponent("runplay-health-extraction-fresh.xml")
        try FileManager.default.createDirectory(at: extractionRoot, withIntermediateDirectories: true)
        try Data("<HealthData/>".utf8).write(to: freshURL)

        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])
        _ = try await makeService().scan(archiveAt: url)

        XCTAssertTrue(
            FileManager.default.fileExists(atPath: freshURL.path),
            "a recent extraction file is not stale and must be left alone"
        )
    }

    /// Too little free space is a clear refusal, not a partial file.
    func testInsufficientFreeSpaceIsRefusedBeforeExtracting() async throws {
        let document = healthDocument(workouts: runningWorkout())
        let url = try writeZip(named: "export.zip", entries: [(Self.exportPath, document)])

        await assertThrows(
            .insufficientFreeSpace(requiredBytes: Int64(document.count), availableBytes: 1)
        ) {
            _ = try await makeService(availableCapacity: 1).scan(archiveAt: url)
        }
        XCTAssertTrue(extractionFileNames().isEmpty)
    }

    // MARK: - Routes

    func testRouteDataIsReturnedForARoutePath() async throws {
        let gpx = routeGPX()
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout(route: "/workout-routes/route_1.gpx"))),
            (Self.routePath, gpx),
        ])

        let data = try await makeService().routeGPXData(
            forArchivePath: Self.routePath,
            archiveAt: url
        )

        XCTAssertEqual(data, gpx)
    }

    func testRouteDataForAnUnknownPathIsRefused() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])

        await assertThrows(.routeEntryNotFound("apple_health_export/workout-routes/missing.gpx")) {
            _ = try await makeService().routeGPXData(
                forArchivePath: "apple_health_export/workout-routes/missing.gpx",
                archiveAt: url
            )
        }
    }

    /// The route reader is not a general entry reader: a path outside the route
    /// directory is refused even though the entry exists.
    func testRouteDataOutsideTheRouteDirectoryIsRefused() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])

        await assertThrows(
            .routePathRejected(path: Self.exportPath, reason: .notUnderRouteDirectory)
        ) {
            _ = try await makeService().routeGPXData(
                forArchivePath: Self.exportPath,
                archiveAt: url
            )
        }
    }

    /// An absolute path is refused rather than trimmed into a relative one.
    func testAbsoluteRoutePathIsRefused() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
            (Self.routePath, routeGPX()),
        ])

        await assertThrows(
            .routePathRejected(path: "/\(Self.routePath)", reason: .absolute)
        ) {
            _ = try await makeService().routeGPXData(
                forArchivePath: "/\(Self.routePath)",
                archiveAt: url
            )
        }
    }

    /// A parent-directory segment is refused, even though resolving it would land
    /// inside the route directory.
    func testParentDirectoryRoutePathIsRefused() async throws {
        let traversing = "apple_health_export/workout-routes/../workout-routes/route_1.gpx"
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
            (Self.routePath, routeGPX()),
        ])

        await assertThrows(.routePathRejected(path: traversing, reason: .traversal)) {
            _ = try await makeService().routeGPXData(
                forArchivePath: traversing,
                archiveAt: url
            )
        }
    }

    /// A backslash is a second separator, not noise: it is refused rather than
    /// unified into a slash.
    func testBackslashRoutePathIsRefused() async throws {
        let backslashed = "apple_health_export\\workout-routes\\route_1.gpx"
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
            (Self.routePath, routeGPX()),
        ])

        await assertThrows(.routePathRejected(path: backslashed, reason: .backslash)) {
            _ = try await makeService().routeGPXData(
                forArchivePath: backslashed,
                archiveAt: url
            )
        }
    }

    /// A symlink under the route directory is refused: following one would let the
    /// archive read outside itself.
    func testSymlinkRouteEntryIsRefused() async throws {
        let linkPath = "apple_health_export/workout-routes/link.gpx"
        let url = try writeArchive(named: "export.zip", entries: [
            (Self.exportPath, .file, healthDocument(workouts: runningWorkout(route: "/workout-routes/link.gpx"))),
            (linkPath, .symlink, Data("../export.xml".utf8)),
        ])

        await assertThrows(.routeEntryIsSymlink(path: linkPath)) {
            _ = try await makeService().routeGPXData(
                forArchivePath: linkPath,
                archiveAt: url
            )
        }
    }

    /// A symlink does not satisfy a workout's route reference, so the reference is
    /// still reported as unmatched.
    func testSymlinkRouteDoesNotSatisfyARouteReference() async throws {
        let linkPath = "apple_health_export/workout-routes/link.gpx"
        let url = try writeArchive(named: "export.zip", entries: [
            (Self.exportPath, .file, healthDocument(workouts: runningWorkout(route: "/workout-routes/link.gpx"))),
            (linkPath, .symlink, Data("../export.xml".utf8)),
        ])

        let result = try await makeService().scan(archiveAt: url)

        XCTAssertEqual(result.report.routeEntryCount, 0)
        XCTAssertEqual(result.report.unmatchedRouteReferenceCount, 1)
    }

    // MARK: - Archive format coverage

    /// The checked-in fixture carries a ZIP64 end-of-central-directory record and
    /// uses a data descriptor for its entry. Both features must import the same
    /// way the equivalent plain archive does.
    ///
    /// The fixture is regenerated by
    /// `Fixtures/make_zip64_descriptor_fixture.py`; its doc comment records why a
    /// hand-rolled generator was needed and what limits were verified.
    func testZip64ArchiveWithDataDescriptorsImportsLikeAPlainArchive() async throws {
        let fixtureURL = try XCTUnwrap(
            Bundle.module.url(
                forResource: "apple-health-zip64-descriptors",
                withExtension: "zip",
                subdirectory: "Fixtures"
            ),
            "the generated ZIP64 fixture is missing from the test bundle"
        )

        // The fixture must genuinely use both features, or the comparison proves
        // nothing about them.
        let bytes = try Data(contentsOf: fixtureURL)
        XCTAssertNotNil(
            bytes.range(of: Data([0x50, 0x4B, 0x06, 0x06])),
            "expected a ZIP64 end-of-central-directory record"
        )
        XCTAssertNotNil(
            bytes.range(of: Data([0x50, 0x4B, 0x06, 0x07])),
            "expected a ZIP64 end-of-central-directory locator"
        )
        let localHeader = try XCTUnwrap(bytes.range(of: Data([0x50, 0x4B, 0x03, 0x04])))
        let firstByte = bytes.startIndex + localHeader.lowerBound
        let flags = UInt16(bytes[firstByte + 6]) | (UInt16(bytes[firstByte + 7]) << 8)
        XCTAssertEqual(flags & 0x0008, 0x0008, "expected the data-descriptor flag")

        let plainURL = try writeZip(named: "plain.zip", entries: [
            (Self.exportPath, healthDocument(
                records: heartRateRecord(value: 141),
                workouts: runningWorkout()
            )),
        ])

        let service = makeService()
        let zip64 = try await service.scan(archiveAt: fixtureURL)
        let plain = try await service.scan(archiveAt: plainURL)

        XCTAssertEqual(zip64.candidates.count, 1)
        XCTAssertEqual(zip64.candidates.map(\.status), plain.candidates.map(\.status))
        XCTAssertEqual(zip64.candidates.map(\.window), plain.candidates.map(\.window))
        XCTAssertEqual(
            zip64.candidates.map { $0.heartRate.map(\.beatsPerMinute) },
            plain.candidates.map { $0.heartRate.map(\.beatsPerMinute) }
        )
        XCTAssertEqual(zip64.candidates.map(\.distanceProvenance), plain.candidates.map(\.distanceProvenance))
        XCTAssertEqual(zip64.report.workoutCount, plain.report.workoutCount)
        XCTAssertEqual(zip64.report.droppedWorkoutCount, plain.report.droppedWorkoutCount)
        XCTAssertEqual(zip64.report.routeEntryCount, plain.report.routeEntryCount)
        XCTAssertEqual(zip64.report.unmatchedRouteReferenceCount, plain.report.unmatchedRouteReferenceCount)
    }

    /// Pins a ZIPFoundation 0.9.20 defect, and the refusal it forces on us.
    ///
    /// `Fixtures/apple-health-zip64-descriptors-offset-sentinel.zip` is the same
    /// synthetic export as the fixture above, written the other way a ZIP64
    /// archive may legitimately express an entry's local-header offset: the real
    /// offset (0, because the entry starts the file) sits in the ZIP64 extra
    /// field, and the central directory's 32-bit slot holds the sentinel
    /// `0xFFFFFFFF`. `unzip` and Python's `zipfile` both read the entry out of it.
    ///
    /// ZIPFoundation 0.9.20 does not. `Entry.CentralDirectoryStructure
    /// .effectiveRelativeOffsetOfLocalHeader` (`Entry.swift:311`) consults the
    /// extra field only when the offset it holds is *greater than zero*, so this
    /// entry's real offset of 0 is discarded in favour of the sentinel.
    /// `Archive.makeIterator` (`Archive.swift:229`) then fails to read a local
    /// file header at that position and ends the sequence early, and the archive
    /// reports **zero entries** despite holding one.
    ///
    /// This test exists so that a silent zero-entry listing cannot pass as an
    /// empty archive, and so that the eventual dependency bump has a tripwire: it
    /// reaches ZIPFoundation directly and asserts the zero-entry listing, so
    /// fixing the library fails this test rather than quietly changing behaviour.
    /// When that happens, this fixture should import like the plain archive above
    /// and both assertions below should be replaced by the comparison.
    ///
    /// Known gap, deliberately left as-is rather than papered over: because the
    /// listing is empty, the scan refuses with `exportXMLNotFound`, whose message
    /// says the ZIP holds no export document. That message is *wrong* for this
    /// archive — the document is in it — so a real export in this layout would
    /// report a misleading reason.
    func testZip64OffsetSentinelArchiveIsRefusedBecauseZIPFoundationListsNoEntries() async throws {
        let fixtureURL = try XCTUnwrap(
            Bundle.module.url(
                forResource: "apple-health-zip64-descriptors-offset-sentinel",
                withExtension: "zip",
                subdirectory: "Fixtures"
            ),
            "the generated ZIP64 offset-sentinel fixture is missing from the test bundle"
        )

        let bytes = try Data(contentsOf: fixtureURL)

        // The archive itself is well formed. Asserting this here keeps the claim
        // precise: a failure below is the library's listing, not a broken fixture.
        XCTAssertNotNil(
            bytes.range(of: Data([0x50, 0x4B, 0x06, 0x06])),
            "expected a ZIP64 end-of-central-directory record"
        )
        XCTAssertNotNil(
            bytes.range(of: Data([0x50, 0x4B, 0x06, 0x07])),
            "expected a ZIP64 end-of-central-directory locator"
        )
        XCTAssertNotNil(
            bytes.range(of: Data(Self.exportPath.utf8)),
            "expected the export entry's name in the archive"
        )
        XCTAssertNotNil(
            bytes.range(of: Data([0x50, 0x4B, 0x03, 0x04])),
            "expected the export entry's local file header"
        )

        // The defect, stated as the library's own observable behaviour.
        let archive = try Archive(url: fixtureURL, accessMode: .read)
        XCTAssertEqual(
            Array(archive).count,
            0,
            "ZIPFoundation listed entries for an entry whose ZIP64 local-header offset is 0. "
                + "If this reached 0.9.21 or later, the library fixed Entry.swift:311 — replace this "
                + "assertion and the refusal below with the plain-archive comparison used above."
        )

        // What the caller sees. A refusal, not a crash and not an empty import.
        do {
            _ = try await makeService().scan(archiveAt: fixtureURL)
            XCTFail("expected the scan to refuse an archive whose sole entry cannot be listed")
        } catch let error as AppleHealthArchiveError {
            XCTAssertEqual(
                error,
                .exportXMLNotFound,
                "the scan must surface the unreadable listing as its existing refusal"
            )
        }
    }

    // MARK: - Cancellation

    func testCancellationBeforeTheScanThrowsAndReturnsNothing() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
        ])

        await assertCancels {
            _ = try await makeService().scan(
                archiveAt: url,
                isCancelled: { true }
            )
        }
        XCTAssertTrue(extractionFileNames().isEmpty)
    }

    func testCancellationBeforeRouteReadThrows() async throws {
        let url = try writeZip(named: "export.zip", entries: [
            (Self.exportPath, healthDocument(workouts: runningWorkout())),
            (Self.routePath, routeGPX()),
        ])

        await assertCancels {
            _ = try await makeService().routeGPXData(
                forArchivePath: Self.routePath,
                archiveAt: url,
                isCancelled: { true }
            )
        }
    }
}

/// A cancellation predicate that counts calls, records the extraction file's mode
/// while it exists, and can start cancelling at a chosen call.
private final class ExtractionProbe: @unchecked Sendable {
    private let lock = NSLock()
    private let directory: URL
    private var calls = 0
    private var observedPermissions: Int?
    private let cancelAt: Int

    init(directory: URL, cancelAt: Int = Int.max) {
        self.directory = directory
        self.cancelAt = cancelAt
    }

    var predicate: @Sendable () -> Bool {
        { [self] in
            lock.lock()
            defer { lock.unlock() }
            calls += 1
            captureFilePermissions()
            return calls >= cancelAt
        }
    }

    /// The extraction file's POSIX permissions, read while the file still exists.
    var filePermissions: Int? {
        lock.lock()
        defer { lock.unlock() }
        return observedPermissions
    }

    private func captureFilePermissions() {
        guard observedPermissions == nil else { return }
        let manager = FileManager.default
        guard let names = try? manager.contentsOfDirectory(atPath: directory.path) else { return }
        for name in names where name.hasPrefix("runplay-health-extraction-") {
            let path = directory.appendingPathComponent(name).path
            guard let attributes = try? manager.attributesOfItem(atPath: path) else { continue }
            observedPermissions = (attributes[.posixPermissions] as? NSNumber)?.intValue
            return
        }
    }
}

/// A cancellation predicate that counts calls and starts cancelling at a point.
private final class CallCounter: @unchecked Sendable {
    private let lock = NSLock()
    private var calls = 0
    private let cancelAt: Int

    init(cancelAt: Int) {
        self.cancelAt = cancelAt
    }

    var callCount: Int {
        lock.lock()
        defer { lock.unlock() }
        return calls
    }

    var predicate: @Sendable () -> Bool {
        { [self] in
            lock.lock()
            defer { lock.unlock() }
            calls += 1
            return calls >= cancelAt
        }
    }
}
