import XCTest
import ZIPFoundation
import RunPlayCore
@testable import RunPlayPlatform

/// Importing selected Apple Health candidates into the library.
///
/// The archives here are built in a temporary directory from generated bytes.
/// Nothing is read from the developer's machine.
final class AppleHealthImportServiceTests: XCTestCase {

    private var tempDir: URL!

    /// A private extraction root under the test's own directory, so the archive
    /// service never writes into the real app caches directory.
    private var extractionRoot: URL {
        tempDir.appendingPathComponent("extractions", isDirectory: true)
    }

    override func setUp() {
        super.setUp()
        tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("AppleHealthImport-\(UUID().uuidString)")
        try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    }

    override func tearDown() {
        // A test that made the library read-only must not leave it that way, or
        // the recursive delete below fails and the next test starts dirty.
        if let tempDir {
            try? FileManager.default.setAttributes(
                [.posixPermissions: 0o755],
                ofItemAtPath: tempDir.path
            )
        }
        try? FileManager.default.removeItem(at: tempDir)
        super.tearDown()
    }

    // MARK: - Fixtures

    private static let exportPath = "apple_health_export/export.xml"
    private static let routePath = "apple_health_export/workout-routes/route_1.gpx"
    /// The reference a workout record carries. Apple writes it without the
    /// export root and with a leading slash; the scan resolves it to `routePath`.
    private static let routeReference = "/workout-routes/route_1.gpx"

    /// A window both sides agree on, so re-importing compares identically.
    private static let runStart: Int64 = 1_756_650_000
    private static let runEnd: Int64 = 1_756_653_600

    private func makeArchiveService() -> AppleHealthArchiveService {
        AppleHealthArchiveService(
            policy: .default,
            extractionRoot: extractionRoot,
            staleExtractionAge: 3_600,
            availableCapacity: { _ in nil }
        )
    }

    private func makeService() -> AppleHealthImportService {
        AppleHealthImportService(archiveService: makeArchiveService())
    }

    private func makeStore(named name: String) -> (FileWorkoutLibraryStore, WorkoutLibraryStoreActor, URL) {
        let root = tempDir.appendingPathComponent(name)
        let store = FileWorkoutLibraryStore(rootURL: root)
        return (store, WorkoutLibraryStoreActor(store: store), root)
    }

    /// Apple's fixed-width timestamp, which is what the export writes.
    private func appleStamp(_ seconds: Int64) -> String {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        formatter.dateFormat = "yyyy-MM-dd HH:mm:ss Z"
        return formatter.string(from: Date(timeIntervalSince1970: TimeInterval(seconds)))
    }

    private func routeGPX(startSeconds: Int64, points: Int = 3) -> Data {
        func stamp(_ offset: Int) -> String {
            let formatter = ISO8601DateFormatter()
            formatter.timeZone = TimeZone(secondsFromGMT: 0)
            return formatter.string(
                from: Date(timeIntervalSince1970: TimeInterval(startSeconds + Int64(offset)))
            )
        }
        var xml = """
        <?xml version="1.0" encoding="UTF-8"?>
        <gpx version="1.1" creator="RunPlayTest"><trk><trkseg>
        """
        for index in 0..<points {
            let lat = 37.77 + Double(index) * 0.001
            xml += """
            <trkpt lat="\(lat)" lon="-122.42"><ele>\(10 + index)</ele><time>\(stamp(index * 30))</time></trkpt>
            """
        }
        xml += "</trkseg></trk></gpx>"
        return Data(xml.utf8)
    }

    /// One workout record, shaped the way the export writes it.
    ///
    /// `route` is the reference the record carries, or nil for a run with no
    /// route at all — the export's own totals are then its only numbers.
    private func workoutRecord(
        startSeconds: Int64,
        endSeconds: Int64,
        route: String? = nil,
        distanceMeters: Double? = nil
    ) -> String {
        let stats = distanceMeters.map {
            "<WorkoutStatistics type=\"HKQuantityTypeIdentifierDistanceWalkingRunning\" "
                + "startDate=\"\(appleStamp(startSeconds))\" endDate=\"\(appleStamp(endSeconds))\" "
                + "sum=\"\($0)\" unit=\"m\"/>"
        } ?? ""
        let body = route.map { "<WorkoutRoute><FileReference path=\"\($0)\"/></WorkoutRoute>" } ?? ""
        return "<Workout workoutActivityType=\"HKWorkoutActivityTypeRunning\" "
            + "startDate=\"\(appleStamp(startSeconds))\" endDate=\"\(appleStamp(endSeconds))\">"
            + "\(stats)\(body)</Workout>"
    }

    private func heartRateRecord(seconds: Int64, bpm: Int = 150) -> String {
        let stamp = appleStamp(seconds)
        return "<Record type=\"HKQuantityTypeIdentifierHeartRate\" value=\"\(bpm)\" "
            + "startDate=\"\(stamp)\" endDate=\"\(stamp)\"/>"
    }

    private func healthDocument(records: String = "", workouts: String = "") -> Data {
        Data("""
        <?xml version="1.0" encoding="UTF-8"?>
        <HealthData locale="en_US">
        \(records)
        \(workouts)
        </HealthData>
        """.utf8)
    }

    private func writeZip(
        named: String,
        entries: [(path: String, data: Data)]
    ) throws -> URL {
        let url = tempDir.appendingPathComponent(named)
        if FileManager.default.fileExists(atPath: url.path) {
            try FileManager.default.removeItem(at: url)
        }
        let archive = try Archive(url: url, accessMode: .create)
        for entry in entries {
            try archive.addEntry(
                with: entry.path,
                type: .file,
                uncompressedSize: Int64(entry.data.count),
                provider: { position, size in
                    let start = Int(position)
                    let end = min(start + size, entry.data.count)
                    return entry.data.subdata(in: start..<end)
                }
            )
        }
        return url
    }

    /// One routed and one route-less workout, so every path in the service is
    /// exercised by the shared fixture.
    ///
    /// The route-less run's start is far enough from the routed one that the two
    /// windows do not touch, so neither is flagged against the other.
    private func makeMixedArchive(
        named: String = "mixed.zip",
        routedStart: Int64 = AppleHealthImportServiceTests.runStart,
        routeLessStart: Int64 = AppleHealthImportServiceTests.runStart + 7_200
    ) throws -> URL {
        return try writeZip(named: named, entries: [
            (Self.exportPath, healthDocument(
                records: [
                    heartRateRecord(seconds: routedStart + 60, bpm: 142),
                    heartRateRecord(seconds: routeLessStart + 60, bpm: 158),
                ].joined(separator: "\n"),
                workouts: [
                    workoutRecord(
                        startSeconds: routedStart,
                        endSeconds: routedStart + 3_600,
                        route: Self.routeReference
                    ),
                    workoutRecord(
                        startSeconds: routeLessStart,
                        endSeconds: routeLessStart + 1_800,
                        distanceMeters: 3_200
                    ),
                ].joined(separator: "\n")
            )),
            (Self.routePath, routeGPX(startSeconds: routedStart)),
        ])
    }

    private func scan(
        _ url: URL,
        existingLibraryRuns: [AppleHealthLibraryRunWindow] = []
    ) async throws -> AppleHealthArchiveScanResult {
        try await makeArchiveService().scan(
            archiveAt: url,
            existingLibraryRuns: existingLibraryRuns
        )
    }

    /// Every workout the library holds, in manifest order.
    ///
    /// A library that was never written has no manifest, which is the empty
    /// library rather than an error — and is exactly the state an import that
    /// rolled back leaves behind.
    private func libraryWorkouts(_ store: FileWorkoutLibraryStore) throws -> [RunWorkout] {
        do {
            return try store.loadManifest().workoutIDs.map { try store.loadWorkout(id: $0) }
        } catch let error as WorkoutLibraryError {
            if case .manifestMissing = error { return [] }
            throw error
        }
    }

    // MARK: - Route window validation

    private func timedGPX(_ offsets: [Int64]) -> Data {
        let formatter = ISO8601DateFormatter()
        let body = offsets.map { offset in
            let time = formatter.string(from: Date(timeIntervalSince1970: Double(Self.runStart + offset)))
            let latitude = 37.77 + Double(offset) * 0.00001
            return "<trkpt lat=\"\(latitude)\" lon=\"-122.42\"><ele>10</ele><time>\(time)</time></trkpt>"
        }.joined()
        return Data("<gpx version=\"1.1\"><trk><trkseg>\(body)</trkseg></trk></gpx>".utf8)
    }

    private func importTimedRoute(
        _ offsets: [Int64], windows: [(Int64, Int64)] = [(0, 600)], recordedOffset: Int = 0,
        heartRate: Bool = true
    ) async throws -> (AppleHealthImportReport, [RunWorkout]) {
        let zip = try writeZip(named: "window.zip", entries: [
            (Self.exportPath, healthDocument(
                records: heartRate
                    ? windows.map { heartRateRecord(seconds: Self.runStart + $0.0 + 60) }.joined()
                    : "",
                workouts: windows.map { workoutRecord(startSeconds: Self.runStart + $0.0,
                    endSeconds: Self.runStart + $0.1, route: Self.routeReference, distanceMeters: 6_000) }.joined()
            )),
            (Self.routePath, timedGPX(offsets)),
        ])
        let result = try await scan(zip)
        var candidates = result.candidates
        for index in candidates.indices { candidates[index].window.utcOffsetSeconds = recordedOffset }
        let (store, actor, _) = makeStore(named: "window-library")
        let report = try await makeService().importSelection(candidates, from: result,
            archiveAt: zip, storeActor: actor)
        return (report, try report.importedWorkoutIDs.map { try store.loadWorkout(id: $0) })
    }

    func testValidRouteAtBothToleranceBoundariesKeepsByteIdenticalSummary() async throws {
        // No heart rate in the export, so nothing is added and the route is exactly
        // what the ordinary GPX import produced.
        let offsets: [Int64] = [-60, 0, 300, 600, 660]
        let original = try GPXImporter().importWorkout(from: WorkoutImportInput(
            data: timedGPX(offsets), fileExtension: "gpx", suggestedName: "route.gpx"))
        let (report, workouts) = try await importTimedRoute(offsets, heartRate: false)
        let workout = try XCTUnwrap(workouts.first)
        let encoder = JSONEncoder(); encoder.outputFormatting = [.sortedKeys]
        XCTAssertEqual(try encoder.encode(workout.summary), try encoder.encode(original.summary))
        XCTAssertEqual(workout.routePoints.map(\.timestamp), original.routePoints.map(\.timestamp))
        XCTAssertEqual(workout.routePoints.map(\.distanceFromStartMeters), original.routePoints.map(\.distanceFromStartMeters))
        XCTAssertNil(workout.summary.averageHeartRateBPM)
        XCTAssertEqual(report.routeWindowMismatchCount, 0)
        XCTAssertEqual(report.trimmedRouteCount, 0)
        XCTAssertEqual(workout.summary.distanceProvenance, .gpsDerived)
    }

    func testValidRouteWithHeartRateDiffersFromTheOrdinaryImportOnlyInHeartRate() async throws {
        let offsets: [Int64] = [-60, 0, 300, 600, 660]
        let original = try GPXImporter().importWorkout(from: WorkoutImportInput(
            data: timedGPX(offsets), fileExtension: "gpx", suggestedName: "route.gpx"))
        let (_, workouts) = try await importTimedRoute(offsets)
        let workout = try XCTUnwrap(workouts.first)

        // The export's reading is the default 150 bpm, and the summary now says so.
        XCTAssertEqual(try XCTUnwrap(workout.summary.averageHeartRateBPM), 150, accuracy: 0.001)
        XCTAssertEqual(workout.summary.maxHeartRateBPM, 150)

        // Everything else is the ordinary GPX import's, field for field.
        var withoutHeartRate = workout.summary
        withoutHeartRate.averageHeartRateBPM = nil
        withoutHeartRate.maxHeartRateBPM = nil
        let encoder = JSONEncoder(); encoder.outputFormatting = [.sortedKeys]
        XCTAssertEqual(try encoder.encode(withoutHeartRate), try encoder.encode(original.summary))

        // Point ids are fresh per import, so compare what each point says. A second
        // analysis pass must not move any derived value on a kept route.
        func shape(_ points: [RoutePoint]) -> [[Double?]] {
            points.map { point in
                [point.timestamp.timeIntervalSince1970, point.distanceFromStartMeters,
                 point.elapsedSeconds, point.altitudeMeters,
                 point.speedMetersPerSecond, point.paceSecondsPerKilometer]
            }
        }
        XCTAssertEqual(shape(workout.routePoints), shape(original.routePoints))
    }

    func testKeptRouteWithHeartRateKeepsItsElevationAndSplitsAfterTheSecondAnalysis() async throws {
        // Altitude that actually varies, so an analysis pass that perturbed the
        // elevation profile or the splits would show in the summary.
        let offsets = Array(stride(from: Int64(0), through: 600, by: 10))
        let formatter = ISO8601DateFormatter()
        let body = offsets.map { offset -> String in
            let time = formatter.string(from: Date(timeIntervalSince1970: Double(Self.runStart + offset)))
            let altitude = 20 + 12 * sin(Double(offset) / 45)
            let latitude = 37.77 + Double(offset) * 0.00004
            return "<trkpt lat=\"\(latitude)\" lon=\"-122.42\"><ele>\(altitude)</ele><time>\(time)</time></trkpt>"
        }.joined()
        let gpx = Data("<gpx version=\"1.1\"><trk><trkseg>\(body)</trkseg></trk></gpx>".utf8)
        let original = try GPXImporter().importWorkout(from: WorkoutImportInput(
            data: gpx, fileExtension: "gpx", suggestedName: "hills.gpx"))
        XCTAssertGreaterThan(original.summary.elevationGainMeters, 0, "the fixture must climb")
        XCTAssertFalse(original.splits.isEmpty, "the fixture must be long enough to split")

        let zip = try writeZip(named: "hills.zip", entries: [
            (Self.exportPath, healthDocument(
                records: heartRateRecord(seconds: Self.runStart + 60),
                workouts: workoutRecord(startSeconds: Self.runStart, endSeconds: Self.runStart + 600,
                    route: Self.routeReference, distanceMeters: 2_700))),
            (Self.routePath, gpx),
        ])
        let result = try await scan(zip)
        let (store, actor, _) = makeStore(named: "hills-library")
        _ = try await makeService().importSelection(result.candidates, from: result,
            archiveAt: zip, storeActor: actor)
        let workout = try XCTUnwrap(try libraryWorkouts(store).first)

        XCTAssertEqual(workout.summary.elevationGainMeters, original.summary.elevationGainMeters, accuracy: 0.000001)
        XCTAssertEqual(workout.summary.elevationLossMeters, original.summary.elevationLossMeters, accuracy: 0.000001)
        XCTAssertEqual(workout.summary.totalDistanceMeters, original.summary.totalDistanceMeters, accuracy: 0.000001)
        XCTAssertEqual(workout.splits.map(\.distanceMeters), original.splits.map(\.distanceMeters))
        XCTAssertEqual(workout.splits.map(\.formattedElapsed), original.splits.map(\.formattedElapsed))
        XCTAssertEqual(workout.segments.map(\.type), original.segments.map(\.type))
    }

    func testSmallOverrunsTrimAndRecomputeGPSAnalysis() async throws {
        for excess: Int64 in [61, 299, 300] {
            let retained = Array(stride(from: Int64(-60), through: 660, by: 30))
            let offsets: [Int64] = [-excess] + retained + [600 + excess]
            let (report, workouts) = try await importTimedRoute(offsets)
            let workout = try XCTUnwrap(workouts.first)
            let expected = try GPXImporter().importWorkout(from: WorkoutImportInput(
                data: timedGPX(retained),
                fileExtension: "gpx", suggestedName: "trimmed.gpx"))
            XCTAssertEqual(report.trimmedRouteCount, 1)
            XCTAssertEqual(report.routeWindowMismatchCount, 0)
            XCTAssertEqual(workout.routePoints.first?.timestamp, Date(timeIntervalSince1970: Double(Self.runStart - 60)))
            XCTAssertEqual(workout.routePoints.last?.timestamp, Date(timeIntervalSince1970: Double(Self.runStart + 660)))
            // The trimmed run carries the export's reading; apart from it, the
            // summary is what the ordinary import of the retained points gives.
            XCTAssertEqual(try XCTUnwrap(workout.summary.averageHeartRateBPM), 150, accuracy: 0.001)
            var withoutHeartRate = workout.summary
            withoutHeartRate.averageHeartRateBPM = nil
            withoutHeartRate.maxHeartRateBPM = nil
            XCTAssertEqual(withoutHeartRate, expected.summary)
            XCTAssertEqual(workout.summary.distanceProvenance, .gpsDerived)
            XCTAssertNotEqual(workout.summary.totalDistanceMeters, 6_000)
        }
    }

    func testTrimmingPreservesRecordingGapsInsteadOfJoiningAcrossThem() async throws {
        let offsets: [Int64] = [-61, -60, 0, 30, 60, 120, 300, 600, 660, 661]
        let original = try GPXImporter().importWorkout(from: WorkoutImportInput(
            data: timedGPX(offsets), fileExtension: "gpx", suggestedName: "gaps.gpx"))
        XCTAssertGreaterThan(original.summary.totalPausedSeconds, 0)
        let retained = Array(original.routePoints.dropFirst().dropLast())
        let (report, workouts) = try await importTimedRoute(offsets)
        let trimmed = try XCTUnwrap(workouts.first)
        XCTAssertEqual(report.trimmedRouteCount, 1)
        XCTAssertEqual(trimmed.summary.totalPausedSeconds, original.summary.totalPausedSeconds)
        XCTAssertEqual(trimmed.summary.totalDistanceMeters,
            retained.last!.distanceFromStartMeters - retained.first!.distanceFromStartMeters,
            accuracy: 0.000001)
        XCTAssertEqual(Set(trimmed.routePoints.map(\.routeSegmentIndex)).count,
            Set(retained.map(\.routeSegmentIndex)).count)
    }

    func testOverFiveMinutesAtEitherEndFallsBackKeepingHRSourceTotalsAndOffset() async throws {
        for offsets: [Int64] in [[-301, 0, 300, 600], [0, 300, 600, 901]] {
            let (report, workouts) = try await importTimedRoute(offsets, recordedOffset: 19_800)
            let workout = try XCTUnwrap(workouts.first)
            XCTAssertEqual(report.routeWindowMismatchCount, 1)
            XCTAssertEqual(report.trimmedRouteCount, 0)
            XCTAssertEqual(report.items.first?.routeFallbackReason, .routeWindowMismatch)
            XCTAssertFalse(workout.hasRoute)
            XCTAssertEqual(workout.summary.distanceProvenance, .sourceReported)
            XCTAssertEqual(workout.summary.totalDistanceMeters, 6_000)
            XCTAssertEqual(workout.summary.totalElapsedSeconds, 600)
            XCTAssertEqual(workout.metadata.recordedUTCOffsetSeconds, 19_800)
            XCTAssertEqual(workout.heartRateSamples.map(\.heartRateBPM), [150])
        }
    }

    func testSharedRouteFitsOneWindowButNotTheOther() async throws {
        let (report, workouts) = try await importTimedRoute([0, 300, 600], windows: [(0, 600), (1_000, 1_600)])
        XCTAssertEqual(report.addedWorkoutCount, 2)
        XCTAssertEqual(report.routeWindowMismatchCount, 1)
        XCTAssertEqual(workouts.filter(\.hasRoute).count, 1)
        XCTAssertEqual(workouts.filter { !$0.hasRoute }.count, 1)
    }

    func testSharedRouteFitsNeitherWindowCountsEachWorkoutAndKeepsHR() async throws {
        let (report, workouts) = try await importTimedRoute([0, 300, 600], windows: [(2_000, 2_600), (4_000, 4_600)])
        XCTAssertEqual(report.routeWindowMismatchCount, 2)
        XCTAssertEqual(workouts.count, 2)
        XCTAssertTrue(workouts.allSatisfy { !$0.hasRoute && $0.summary.distanceProvenance == .sourceReported })
        XCTAssertTrue(workouts.allSatisfy { $0.heartRateSamples.map(\.heartRateBPM) == [150] })
    }

    func testNoOverlapEvenInsideToleranceFallsBack() async throws {
        let (report, workouts) = try await importTimedRoute([-50, -10])
        XCTAssertEqual(report.routeWindowMismatchCount, 1)
        XCTAssertFalse(try XCTUnwrap(workouts.first).hasRoute)
    }

    // MARK: - Route provenance

    func testRoutedCandidateImportsWithGPSDerivedDistance() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        let routed = try XCTUnwrap(result.candidates.first { $0.hasRoute })

        let (store, storeActor, _) = makeStore(named: "lib-routed")
        let report = try await makeService().importSelection(
            [routed],
            from: result,
            archiveAt: zip,
            storeActor: storeActor
        )

        XCTAssertEqual(report.importedCount, 1)
        XCTAssertEqual(report.importedWithoutRouteCount, 0)
        XCTAssertFalse(report.wasCancelled)
        XCTAssertFalse(report.commitFailed)

        let workout = try XCTUnwrap(try libraryWorkouts(store).first)
        XCTAssertEqual(workout.summary.distanceProvenance, .gpsDerived)
        XCTAssertFalse(workout.routePoints.isEmpty, "a routed import must carry its route")
        XCTAssertEqual(workout.source, .healthKit)
        XCTAssertEqual(workout.metadata.recordedUTCOffsetSeconds, 0)
        XCTAssertEqual(workout.importProvenance?.provider, .appleHealthExport)
        XCTAssertEqual(workout.importProvenance?.providerActivityID, routed.id)
        XCTAssertNotNil(workout.importProvenance?.contentSHA256)
    }

    func testRouteLessCandidateImportsAsSourceReportedAndKeepsHeartRate() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        let routeLess = try XCTUnwrap(result.candidates.first { !$0.hasRoute })

        let (store, storeActor, _) = makeStore(named: "lib-routeless")
        let report = try await makeService().importSelection(
            [routeLess],
            from: result,
            archiveAt: zip,
            storeActor: storeActor
        )

        XCTAssertEqual(report.importedCount, 1)

        let workout = try XCTUnwrap(try libraryWorkouts(store).first)
        XCTAssertTrue(workout.routePoints.isEmpty)
        XCTAssertEqual(workout.summary.distanceProvenance, .sourceReported)
        XCTAssertEqual(workout.summary.totalDistanceMeters, 3_200, accuracy: 0.001)
        XCTAssertEqual(workout.summary.totalElapsedSeconds, 1_800, accuracy: 0.001)
        XCTAssertEqual(workout.source, .healthKit)
        XCTAssertNil(workout.importProvenance?.contentSHA256, "a route-less run has no source file to hash")

        // The heart rate the scan joined to this window survives the import.
        let series = try XCTUnwrap(workout.heartRateSeries)
        XCTAssertEqual(series.count, 1)
        XCTAssertEqual(series[0].heartRateBPM, 158)
        XCTAssertEqual(series[0].elapsedSeconds, 60, accuracy: 0.001)
    }

    // MARK: - Summary heart rate

    /// One routed and one route-less run whose windows never touch, each with
    /// the readings given for it (none for an empty array).
    private func makeHeartRateArchive(routedBPM: [Int], routeLessBPM: [Int]) throws -> URL {
        let routedStart = Self.runStart
        let routeLessStart = Self.runStart + 7_200
        func readings(_ values: [Int], from start: Int64) -> [String] {
            values.enumerated().map { offset, bpm in
                heartRateRecord(seconds: start + 60 * Int64(offset + 1), bpm: bpm)
            }
        }
        return try writeZip(named: "heart-rate-summary.zip", entries: [
            (Self.exportPath, healthDocument(
                records: (readings(routedBPM, from: routedStart)
                    + readings(routeLessBPM, from: routeLessStart)).joined(separator: "\n"),
                workouts: [
                    workoutRecord(startSeconds: routedStart, endSeconds: routedStart + 3_600,
                        route: Self.routeReference),
                    workoutRecord(startSeconds: routeLessStart, endSeconds: routeLessStart + 1_800,
                        distanceMeters: 3_200),
                ].joined(separator: "\n")
            )),
            (Self.routePath, routeGPX(startSeconds: routedStart)),
        ])
    }

    private func importBothRuns(
        routedBPM: [Int], routeLessBPM: [Int]
    ) async throws -> (routed: RunWorkout, routeLess: RunWorkout) {
        let zip = try makeHeartRateArchive(routedBPM: routedBPM, routeLessBPM: routeLessBPM)
        let result = try await scan(zip)
        XCTAssertEqual(result.candidates.count, 2)
        let (store, storeActor, _) = makeStore(named: "heart-rate-summary-library")
        let report = try await makeService().importSelection(
            result.candidates, from: result, archiveAt: zip, storeActor: storeActor
        )
        XCTAssertEqual(report.importedCount, 2)
        let workouts = try libraryWorkouts(store)
        return (
            try XCTUnwrap(workouts.first { $0.hasRoute }),
            try XCTUnwrap(workouts.first { !$0.hasRoute })
        )
    }

    func testImportedRunsCarryAverageAndMaximumHeartRateInTheirSummaries() async throws {
        // 25 and 240 bpm are outside the range the analyzer accepts, so they are
        // not part of either number.
        let (routed, routeLess) = try await importBothRuns(
            routedBPM: [140, 150, 160, 25, 240],
            routeLessBPM: [120, 130, 140]
        )

        XCTAssertEqual(try XCTUnwrap(routed.summary.averageHeartRateBPM), 150, accuracy: 0.001)
        XCTAssertEqual(routed.summary.maxHeartRateBPM, 160)
        XCTAssertEqual(try XCTUnwrap(routeLess.summary.averageHeartRateBPM), 130, accuracy: 0.001)
        XCTAssertEqual(routeLess.summary.maxHeartRateBPM, 140)
    }

    func testImportedRunsWithoutHeartRateHaveNoSummaryHeartRateRatherThanZero() async throws {
        let (routed, routeLess) = try await importBothRuns(routedBPM: [], routeLessBPM: [])

        for workout in [routed, routeLess] {
            XCTAssertNil(workout.heartRateSeries)
            XCTAssertNil(workout.summary.averageHeartRateBPM, "absent, not 0")
            XCTAssertNil(workout.summary.maxHeartRateBPM, "absent, not 0")
        }
    }

    func testRunsWhoseOnlyReadingsAreOutOfRangeHaveNoSummaryHeartRateEither() async throws {
        let (routed, routeLess) = try await importBothRuns(routedBPM: [25, 240], routeLessBPM: [10, 250])

        for workout in [routed, routeLess] {
            XCTAssertNil(workout.summary.averageHeartRateBPM, "no valid reading means no average, not 0")
            XCTAssertNil(workout.summary.maxHeartRateBPM)
        }
    }

    func testRouteLessSummaryIsWhatTheAnalyzerMakesFromTheExportsTotals() async throws {
        let (_, routeLess) = try await importBothRuns(routedBPM: [], routeLessBPM: [150])

        // The analyzer's route-less path is the only thing that builds this
        // summary, so an equivalent workout analysed directly matches it.
        var expected = RunWorkout(
            summary: RunSummary(totalDistanceMeters: 3_200, totalElapsedSeconds: 1_800),
            analysisVersion: RunWorkout.currentAnalysisVersion,
            heartRateSeries: [HeartRateSample(elapsedSeconds: 60, heartRateBPM: 150, segmentIndex: 0)]
        )
        WorkoutAnalyzer().analyze(&expected)
        XCTAssertEqual(routeLess.summary, expected.summary)
        XCTAssertEqual(routeLess.summary.distanceProvenance, .sourceReported)
        XCTAssertEqual(try XCTUnwrap(routeLess.summary.averageHeartRateBPM), 150, accuracy: 0.001)

        // The analysis version is the current one, not a new one.
        XCTAssertEqual(routeLess.analysisVersion, RunWorkout.currentAnalysisVersion)
        // No GPS, so no note about GPS reliability.
        XCTAssertFalse(routeLess.analysisWarnings.contains(.movementLowReliability))
    }

    func testRoutedCandidateWhoseRouteIsAbsentIsImportedWithoutItAndSaysSo() async throws {
        // The workout names a route file the archive does not contain. The scan
        // counts it as an unmatched reference; the import must still bring the
        // run in, and must not pretend it has a route.
        let zip = try writeZip(named: "missing-route.zip", entries: [
            (Self.exportPath, healthDocument(workouts: workoutRecord(
                startSeconds: Self.runStart,
                endSeconds: Self.runStart + 1_800,
                route: "/workout-routes/route_absent.gpx",
                distanceMeters: 4_100
            ))),
        ])

        let result = try await scan(zip)
        XCTAssertEqual(result.report.unmatchedRouteReferenceCount, 1)

        let (store, storeActor, _) = makeStore(named: "lib-missing-route")
        let report = try await makeService().importSelection(
            result.candidates,
            from: result,
            archiveAt: zip,
            storeActor: storeActor
        )

        XCTAssertEqual(report.importedWithoutRouteCount, 1)
        XCTAssertEqual(report.importedCount, 0)
        XCTAssertEqual(report.failedCount, 0)
        let detail = try XCTUnwrap(report.items.first?.detail)
        XCTAssertTrue(
            detail.contains("without its route"),
            "the item must say the route was unavailable, got: \(detail)"
        )

        let workout = try XCTUnwrap(try libraryWorkouts(store).first)
        XCTAssertTrue(workout.routePoints.isEmpty)
        XCTAssertEqual(workout.summary.distanceProvenance, .sourceReported)
    }

    // MARK: - Report counts

    func testImportReportCarriesExclusionsEvenWhenNothingIsSelected() async throws {
        let run = workoutRecord(startSeconds: Self.runStart, endSeconds: Self.runEnd)
        let excluded = run.replacingOccurrences(of: "HKWorkoutActivityTypeRunning", with: "HKWorkoutActivityTypeCycling")
        let zip = try writeZip(named: "excluded.zip", entries: [
            (Self.exportPath, healthDocument(workouts: run + excluded + excluded)),
        ])
        let result = try await scan(zip)
        let (store, actor, _) = makeStore(named: "lib-exclusions")
        for selected in [[], result.candidates] {
            let report = try await makeService().importSelection(
                selected, from: result, archiveAt: zip, storeActor: actor
            )
            XCTAssertEqual(report.excludedWorkoutsByActivityType, ["HKWorkoutActivityTypeCycling": 2])
            XCTAssertEqual(report.excludedWorkoutCount, 2)
            XCTAssertEqual(report.addedWorkoutCount, selected.count)
        }
        XCTAssertEqual(try store.loadManifest().workoutIDs.count, 1)
    }

    func testReportCarriesTheArchiveLossCountsBesideTheItemOutcomes() async throws {
        // A document the scan cannot build a workout from, plus a workout naming
        // an absent route: one dropped, one unmatched.
        let unreadable = "<Workout workoutActivityType=\"HKWorkoutActivityTypeRunning\" "
            + "startDate=\"not-a-date\" endDate=\"also-not-a-date\"/>"
        let zip = try writeZip(named: "losses.zip", entries: [
            (Self.exportPath, healthDocument(workouts: unreadable + workoutRecord(
                startSeconds: Self.runStart,
                endSeconds: Self.runStart + 1_800,
                route: "/workout-routes/route_absent.gpx",
                distanceMeters: 4_100
            ))),
        ])

        let result = try await scan(zip)
        XCTAssertEqual(result.report.droppedWorkoutCount, 1)
        XCTAssertEqual(result.report.unmatchedRouteReferenceCount, 1)

        let (_, storeActor, _) = makeStore(named: "lib-losses")
        let report = try await makeService().importSelection(
            result.candidates,
            from: result,
            archiveAt: zip,
            storeActor: storeActor
        )

        XCTAssertEqual(report.droppedWorkoutCount, 1)
        XCTAssertEqual(report.unmatchedRouteReferenceCount, 1)
        XCTAssertEqual(report.importedWithoutRouteCount, 1)
    }

    // MARK: - Idempotency

    func testImportingTheSameExportTwiceAddsNothingTheSecondTime() async throws {
        let zip = try makeMixedArchive()
        let (store, storeActor, _) = makeStore(named: "lib-twice")

        // First pass: nothing in the library, so nothing to compare against.
        let first = try await scan(zip)
        let firstReport = try await makeService().importSelection(
            first.candidates,
            from: first,
            archiveAt: zip,
            storeActor: storeActor
        )
        XCTAssertEqual(firstReport.addedWorkoutCount, 2)
        let afterFirst = try libraryWorkouts(store)
        XCTAssertEqual(afterFirst.count, 2)

        // Second pass, over the same archive with the library as it now stands.
        // The candidates are force-selected wholesale, so this cannot pass by
        // the review having unchecked them.
        let second = try await scan(zip)
        let secondReport = try await makeService().importSelection(
            second.candidates,
            from: second,
            archiveAt: zip,
            existingWorkouts: try libraryWorkouts(store),
            storeActor: storeActor
        )

        XCTAssertEqual(secondReport.addedWorkoutCount, 0)
        XCTAssertEqual(secondReport.items.count, 2)
        XCTAssertTrue(
            secondReport.items.allSatisfy { $0.outcome == .alreadyInLibrary },
            "every candidate should be recognised as already imported, got "
                + "\(secondReport.items.map(\.outcome))"
        )
        XCTAssertEqual(secondReport.alreadyInLibraryCount, 2)

        let afterSecond = try libraryWorkouts(store)
        XCTAssertEqual(afterSecond.count, 2)
        XCTAssertEqual(Set(afterSecond.map(\.id)), Set(afterFirst.map(\.id)))
    }

    func testCandidateOverlappingALibraryRunButNotMatchingItIsStillImported() async throws {
        // Idempotency must be exact, not loose: a genuinely different run that
        // merely overlaps one already stored is a run the user did, and skipping
        // it would lose data.
        let zip = try makeMixedArchive()
        let (_, storeActor, _) = makeStore(named: "lib-overlap")

        let overlapping = AppleHealthLibraryRunWindow(
            startSeconds: Self.runStart + 300,
            endSeconds: Self.runEnd + 300
        )
        let result = try await scan(zip, existingLibraryRuns: [overlapping])
        let report = try await makeService().importSelection(
            result.candidates,
            from: result,
            archiveAt: zip,
            existingWorkouts: [Self.libraryRun(startSeconds: Self.runStart + 300, endSeconds: Self.runEnd + 300)],
            storeActor: storeActor
        )

        XCTAssertEqual(report.alreadyInLibraryCount, 0)
        XCTAssertEqual(report.addedWorkoutCount, 2)
    }

    private static func libraryRun(startSeconds: Int64, endSeconds: Int64) -> RunWorkout {
        RunWorkout(
            metadata: WorkoutMetadata(
                startDate: Date(timeIntervalSince1970: TimeInterval(startSeconds)),
                endDate: Date(timeIntervalSince1970: TimeInterval(endSeconds))
            ),
            analysisVersion: RunWorkout.currentAnalysisVersion
        )
    }

    // MARK: - Atomicity

    func testCancellingMidStagingLeavesTheLibraryUnchanged() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        XCTAssertEqual(result.candidates.count, 2)
        let (store, storeActor, _) = makeStore(named: "lib-cancel")

        // Cancel from the first staging progress report, which arrives after one
        // workout has already been handed to the library's staging area. The
        // batch must therefore be rolled back rather than left half-promoted.
        let cancelled = Atomic(false)
        let service = makeService()
        let report = try await service.importSelection(
            result.candidates,
            from: result,
            archiveAt: zip,
            storeActor: storeActor,
            progress: { progress in
                if progress.phase == .staging { cancelled.set(true) }
            },
            isCancelled: { cancelled.value }
        )

        XCTAssertTrue(report.wasCancelled)
        XCTAssertEqual(report.addedWorkoutCount, 0)
        XCTAssertFalse(report.commitFailed)
        // The cancellation landed after the first workout was staged, which is
        // what makes this a test of the rollback rather than of the early exit.
        XCTAssertEqual(report.items.count, 1, "expected to stop after the first candidate staged")
        XCTAssertEqual(report.discardedCount, 1)
        XCTAssertEqual(report.importedCount, 0, "a discarded workout must not be reported as imported")
        XCTAssertTrue(try libraryWorkouts(store).isEmpty, "a cancelled import must add nothing")
        let hasActiveBatch = await storeActor.hasActiveBatch
        XCTAssertFalse(hasActiveBatch, "a cancelled import must release the batch")
    }

    func testFailingMidCommitLeavesTheLibraryUnchanged() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        let (store, storeActor, libraryRoot) = makeStore(named: "lib-commit-fail")

        // Make the library directory read-only at the moment the pass is about to
        // commit. Staging has already succeeded and the promote cannot, which is
        // the failure the batch seam has to survive with the library untouched.
        let service = makeService()
        let report = try await service.importSelection(
            result.candidates,
            from: result,
            archiveAt: zip,
            storeActor: storeActor,
            progress: { progress in
                guard progress.phase == .committing else { return }
                try? FileManager.default.setAttributes(
                    [.posixPermissions: 0o555],
                    ofItemAtPath: libraryRoot.path
                )
            }
        )

        XCTAssertTrue(report.commitFailed, "the commit was expected to fail")
        XCTAssertNotNil(report.errorMessage)
        XCTAssertEqual(report.addedWorkoutCount, 0)
        XCTAssertEqual(report.importedCount, 0, "nothing that was staged may be reported as imported")
        XCTAssertEqual(report.discardedCount, result.candidates.count)
        XCTAssertEqual(report.failedCount, 0, "a rolled-back workout is discarded, not failed")

        // Restore write access before inspecting, then assert the library is as
        // it was: no manifest, no promoted snapshots.
        try? FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: libraryRoot.path
        )
        XCTAssertTrue(try libraryWorkouts(store).isEmpty, "a failed commit must add nothing")
    }

    func testEmptySelectionDoesNotTakeTheLibraryBatch() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        let (_, storeActor, _) = makeStore(named: "lib-empty")

        let report = try await makeService().importSelection(
            [],
            from: result,
            archiveAt: zip,
            storeActor: storeActor
        )

        XCTAssertTrue(report.items.isEmpty)
        XCTAssertEqual(report.addedWorkoutCount, 0)
        // The report still states what the export itself lost.
        XCTAssertEqual(report.droppedWorkoutCount, result.report.droppedWorkoutCount)
        XCTAssertEqual(report.unmatchedRouteReferenceCount, result.report.unmatchedRouteReferenceCount)
        // Nothing was staged, so the batch lock must not have been taken at all.
        let hasActiveBatch = await storeActor.hasActiveBatch
        XCTAssertFalse(hasActiveBatch)
    }

    func testImportRefusesANonLocalArchive() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        let (_, storeActor, _) = makeStore(named: "lib-nonfile")

        let remote = try XCTUnwrap(URL(string: "https://example.com/export.zip"))
        do {
            _ = try await makeService().importSelection(
                result.candidates,
                from: result,
                archiveAt: remote,
                storeActor: storeActor
            )
            XCTFail("expected a non-file archive to be refused")
        } catch let error as AppleHealthImportError {
            XCTAssertEqual(error, .notALocalFile)
        }
    }

    // MARK: - Progress

    func testProgressReportsEveryPhaseAndEndsCompleted() async throws {
        let zip = try makeMixedArchive()
        let result = try await scan(zip)
        let (_, storeActor, _) = makeStore(named: "lib-progress")

        let phases = Atomic<[AppleHealthImportProgress.Phase]>([])
        let totals = Atomic<[Int]>([])
        _ = try await makeService().importSelection(
            result.candidates,
            from: result,
            archiveAt: zip,
            storeActor: storeActor,
            progress: { progress in
                phases.mutate { $0.append(progress.phase) }
                totals.mutate { $0.append(progress.totalCount) }
            }
        )

        XCTAssertEqual(phases.value.first, .importing)
        XCTAssertEqual(phases.value.last, .completed)
        XCTAssertTrue(phases.value.contains(.staging))
        XCTAssertTrue(phases.value.contains(.committing))
        XCTAssertTrue(totals.value.allSatisfy { $0 == 2 })
    }
}

/// A tiny lock-free box the progress closures can write from another task.
///
/// `XCTest` closures here are `@Sendable` and may run on the service's actor, so
/// the test cannot keep the state in a captured `var`.
private final class Atomic<Value>: @unchecked Sendable {
    private let lock = NSLock()
    private var storage: Value

    init(_ value: Value) {
        storage = value
    }

    var value: Value {
        lock.lock()
        defer { lock.unlock() }
        return storage
    }

    func set(_ value: Value) {
        lock.lock()
        storage = value
        lock.unlock()
    }

    func mutate(_ body: (inout Value) -> Void) {
        lock.lock()
        body(&storage)
        lock.unlock()
    }
}
