import Foundation

/// JSON-serializable workout summary with explicit clock semantics.
public struct WorkoutExportSummary: Codable, Sendable {
    public let appName: String
    public let exportVersion: String
    public let exportDate: Date
    public let privacyNote: String
    public let workoutTitle: String
    public let source: String
    public let startDate: Date?
    public let endDate: Date?
    public let routePointCount: Int
    public let normalizationVersion: Int
    public let routeDistanceSource: String
    public let routeDistanceSegmentSources: [String]
    public let elevationAnalysis: String
    public let elevationAnalysisAvailable: Bool
    /// Which altitude the elevation figures were computed from.
    public let elevationSource: ElevationSourceExport
    public let qualityDiagnostics: RouteQualityDiagnostics
    public let analysisWarnings: [String]
    public let movementDiagnostics: MovementDiagnostics

    public let totalDistanceMeters: Double
    public let totalElapsedSeconds: Double
    public let totalActiveSeconds: Double
    public let totalPausedSeconds: Double
    public let totalMovingSeconds: Double
    public let totalStoppedSeconds: Double
    public let movingPaceSecondsPerKilometer: Double
    public let movingAverageSpeedMetersPerSecond: Double
    public let activePaceSecondsPerKilometer: Double
    public let elapsedPaceSecondsPerKilometer: Double
    public let activeAverageSpeedMetersPerSecond: Double
    public let elapsedAverageSpeedMetersPerSecond: Double

    /// Additive v1 compatibility aliases. Duration means elapsed; average pace
    /// and speed retain their active semantics.
    public let totalDurationSeconds: Double
    public let averagePaceSecondsPerKilometer: Double
    public let averageSpeedMetersPerSecond: Double

    public let elevationGainMeters: Double
    public let elevationLossMeters: Double
    public let averageHeartRateBPM: Double?
    public let maxHeartRateBPM: Double?
    /// Running power (watts). Nil keys throughout when the source carried none.
    public let averagePowerWatts: Double?
    public let maxPowerWatts: Double?
    public let best20MinutePowerWatts: Double?
    /// Running-dynamics averages; nil when the source carried no dynamics.
    public let runningDynamics: RunningDynamicsExport?
    /// FIT developer-field provenance and diagnostics, when present.
    public let developerFields: WorkoutDeveloperFieldSummary?
    public let splits: [SplitExport]
    public let recordedLaps: [RecordedLapExport]
    public let recordedLapDiagnostics: RecordedLapDiagnostics
    public let sourceStructureVersion: Int
    public let segments: [SegmentExport]

    public init(workout: RunWorkout, segments: [SegmentHighlight]) {
        appName = "RunPlay Studio"
        exportVersion = "4.2"
        exportDate = Date()
        privacyNote = "Local export generated by RunPlay Studio. No data was uploaded to any server."
        workoutTitle = workout.displayName
        source = workout.source.rawValue
        startDate = workout.metadata.startDate
        endDate = workout.metadata.endDate
        routePointCount = workout.routePoints.count
        normalizationVersion = workout.normalizationVersion
        routeDistanceSource = workout.routeDistanceSource.rawValue
        routeDistanceSegmentSources = workout.routeDistanceProvenance.segmentSources.map(\.rawValue)
        elevationAnalysis = "Distance-smoothed altitude with threshold-confirmed ascent and descent"
        let elevationProfile = ElevationProfile(routePoints: workout.routePoints)
        elevationAnalysisAvailable = elevationProfile.hasMeaningfulElevation
        elevationSource = ElevationSourceExport(workout: workout, sourceCounts: elevationProfile.sourceCounts)
        qualityDiagnostics = workout.qualityDiagnostics
        analysisWarnings = workout.analysisWarnings.map(\.message)
        movementDiagnostics = workout.movementDiagnostics

        let summary = workout.summary
        totalDistanceMeters = ExportMetricSanitizer.nonNegative(summary.totalDistanceMeters)
        totalElapsedSeconds = ExportMetricSanitizer.nonNegative(summary.totalElapsedSeconds)
        totalActiveSeconds = ExportMetricSanitizer.nonNegative(summary.totalActiveSeconds)
        totalPausedSeconds = ExportMetricSanitizer.nonNegative(summary.totalPausedSeconds)
        totalMovingSeconds = ExportMetricSanitizer.nonNegative(summary.totalMovingSeconds)
        totalStoppedSeconds = ExportMetricSanitizer.nonNegative(summary.totalStoppedSeconds)
        movingPaceSecondsPerKilometer = ExportMetricSanitizer.nonNegative(summary.movingPaceSecondsPerKilometer)
        movingAverageSpeedMetersPerSecond = ExportMetricSanitizer.nonNegative(summary.movingAverageSpeedMetersPerSecond)
        activePaceSecondsPerKilometer = ExportMetricSanitizer.nonNegative(summary.averagePaceSecondsPerKilometer)
        elapsedPaceSecondsPerKilometer = ExportMetricSanitizer.nonNegative(summary.elapsedPaceSecondsPerKilometer)
        activeAverageSpeedMetersPerSecond = ExportMetricSanitizer.nonNegative(summary.averageSpeedMetersPerSecond)
        elapsedAverageSpeedMetersPerSecond = ExportMetricSanitizer.nonNegative(summary.elapsedAverageSpeedMetersPerSecond)
        totalDurationSeconds = totalElapsedSeconds
        averagePaceSecondsPerKilometer = activePaceSecondsPerKilometer
        averageSpeedMetersPerSecond = activeAverageSpeedMetersPerSecond
        elevationGainMeters = ExportMetricSanitizer.nonNegative(summary.elevationGainMeters)
        elevationLossMeters = ExportMetricSanitizer.nonNegative(summary.elevationLossMeters)
        averageHeartRateBPM = ExportMetricSanitizer.optional(summary.averageHeartRateBPM)
        maxHeartRateBPM = ExportMetricSanitizer.optional(summary.maxHeartRateBPM)
        averagePowerWatts = ExportMetricSanitizer.optional(summary.averagePowerWatts)
        maxPowerWatts = ExportMetricSanitizer.optional(summary.maxPowerWatts)
        best20MinutePowerWatts = ExportMetricSanitizer.optional(summary.best20MinutePowerWatts)
        runningDynamics = RunningDynamicsExport(summary: summary)
        developerFields = workout.developerFieldSummary
        splits = workout.splits.map(SplitExport.init)
        recordedLaps = workout.recordedLaps.map(RecordedLapExport.init)
        recordedLapDiagnostics = workout.recordedLapDiagnostics
        sourceStructureVersion = workout.sourceStructureVersion
        self.segments = segments.map(SegmentExport.init)
    }
}

/// Where exported elevation came from: recorded altitude, DEM elevation, or
/// both, and the last DEM correction without the tile folder's identity.
public struct ElevationSourceExport: Codable, Sendable {
    /// `none`, `recorded`, `dem`, or `demAndRecorded`.
    public let source: String
    /// `barometric` or `unknown`: what the source file says about the sensor
    /// behind its recorded altitude.
    public let recordedAltitudeSensor: String
    public let demPointCount: Int
    public let recordedPointCount: Int
    /// `nil` when the workout was never DEM-corrected.
    public let demCorrection: DEMCorrectionExport?

    init(workout: RunWorkout, sourceCounts: ElevationSourceCounts) {
        let summary = ElevationSourceSummary(workout: workout, sourceCounts: sourceCounts)
        source = summary.source.rawValue
        recordedAltitudeSensor = workout.recordedAltitudeSensor == .barometric ? "barometric" : "unknown"
        demPointCount = sourceCounts.demPointCount
        recordedPointCount = sourceCounts.recordedPointCount
        demCorrection = workout.demElevationCorrection.map(DEMCorrectionExport.init)
    }
}

public struct DEMCorrectionExport: Codable, Sendable {
    /// `applied`, `noCoverage`, `tileBudgetExceeded`, or `optedOut`.
    public let outcome: String
    public let correctedAt: Date
    public let zoom: Int?
    public let tileSize: Int?
    /// Share of the points a tile could cover that a present tile covered.
    public let tileCoverageFraction: Double?
    public let replacedRecordedPointCount: Int
    public let filledMissingPointCount: Int
    public let keptBarometricPointCount: Int
    public let missingTileCount: Int
    public let unreadableTileCount: Int

    init(_ correction: DEMElevationCorrection) {
        outcome = correction.outcome.name
        correctedAt = correction.correctedAt
        zoom = correction.tileSet?.zoom
        tileSize = correction.tileSet?.tileSize
        tileCoverageFraction = correction.coverage.tileCoverageFraction
        replacedRecordedPointCount = correction.coverage.replacedRecordedPointCount
        filledMissingPointCount = correction.coverage.filledMissingPointCount
        keptBarometricPointCount = correction.coverage.keptBarometricPointCount
        missingTileCount = correction.coverage.missingTileCount
        unreadableTileCount = correction.coverage.unreadableTileCount
    }
}

public struct RecordedLapExport: Codable, Sendable {
    public let lapIndex: Int
    public let trigger: String
    public let startElapsedSeconds: Double
    public let endElapsedSeconds: Double
    public let startDistanceKm: Double
    public let endDistanceKm: Double
    public let distanceKm: Double
    public let elapsedDurationSeconds: Double
    public let activeDurationSeconds: Double
    public let movingDurationSeconds: Double
    public let stoppedDurationSeconds: Double
    public let pausedDurationSeconds: Double
    public let movingPaceSecondsPerKilometer: Double
    public let activePaceSecondsPerKilometer: Double
    public let elapsedPaceSecondsPerKilometer: Double
    public let elevationGainMeters: Double?
    public let elevationLossMeters: Double?
    public let averageHeartRateBPM: Double?
    public let maximumHeartRateBPM: Double?
    public let averageCadence: Double?
    public let reportedMetrics: RecordedLapReportedMetrics?

    public init(lap: RecordedLap) {
        let sanitized = lap.sanitized()
        lapIndex = sanitized.lapIndex
        trigger = sanitized.trigger.exportToken
        startElapsedSeconds = ExportMetricSanitizer.nonNegative(sanitized.startElapsedSeconds)
        endElapsedSeconds = ExportMetricSanitizer.nonNegative(sanitized.endElapsedSeconds)
        startDistanceKm = ExportMetricSanitizer.nonNegative(sanitized.startDistanceMeters) / 1000
        endDistanceKm = ExportMetricSanitizer.nonNegative(sanitized.endDistanceMeters) / 1000
        distanceKm = ExportMetricSanitizer.nonNegative(sanitized.distanceMeters) / 1000
        elapsedDurationSeconds = ExportMetricSanitizer.nonNegative(sanitized.elapsedSeconds)
        activeDurationSeconds = ExportMetricSanitizer.nonNegative(sanitized.activeSeconds)
        movingDurationSeconds = ExportMetricSanitizer.nonNegative(sanitized.movingSeconds)
        stoppedDurationSeconds = ExportMetricSanitizer.nonNegative(sanitized.stoppedSeconds)
        pausedDurationSeconds = ExportMetricSanitizer.nonNegative(sanitized.pausedSeconds)
        movingPaceSecondsPerKilometer = ExportMetricSanitizer.nonNegative(
            sanitized.movingPaceSecondsPerKilometer
        )
        activePaceSecondsPerKilometer = ExportMetricSanitizer.nonNegative(
            sanitized.activePaceSecondsPerKilometer
        )
        elapsedPaceSecondsPerKilometer = ExportMetricSanitizer.nonNegative(
            sanitized.elapsedPaceSecondsPerKilometer
        )
        elevationGainMeters = ExportMetricSanitizer.optional(sanitized.elevationGainMeters)
        elevationLossMeters = ExportMetricSanitizer.optional(sanitized.elevationLossMeters)
        averageHeartRateBPM = ExportMetricSanitizer.optional(sanitized.averageHeartRateBPM)
        maximumHeartRateBPM = ExportMetricSanitizer.optional(sanitized.maximumHeartRateBPM)
        averageCadence = ExportMetricSanitizer.optional(sanitized.averageCadence)
        reportedMetrics = sanitized.reportedMetrics
    }
}

/// Running-dynamics averages with unit-explicit names. Every field is nil
/// when the workout's source carried no such samples.
public struct RunningDynamicsExport: Codable, Sendable {
    public let averageGroundContactTimeMilliseconds: Double?
    public let averageVerticalOscillationMillimeters: Double?
    public let averageVerticalRatioPercent: Double?
    public let averageStanceTimeBalancePercent: Double?
    public let averageStepLengthMeters: Double?

    init(summary: RunSummary) {
        let hasDynamics =
            summary.averageGroundContactTimeMilliseconds != nil
            || summary.averageVerticalOscillationMillimeters != nil
            || summary.averageVerticalRatioPercent != nil
            || summary.averageStanceTimeBalancePercent != nil
            || summary.averageStepLengthMeters != nil
        guard hasDynamics else {
            averageGroundContactTimeMilliseconds = nil
            averageVerticalOscillationMillimeters = nil
            averageVerticalRatioPercent = nil
            averageStanceTimeBalancePercent = nil
            averageStepLengthMeters = nil
            return
        }
        averageGroundContactTimeMilliseconds = ExportMetricSanitizer.optional(
            summary.averageGroundContactTimeMilliseconds
        )
        averageVerticalOscillationMillimeters = ExportMetricSanitizer.optional(
            summary.averageVerticalOscillationMillimeters
        )
        averageVerticalRatioPercent = ExportMetricSanitizer.optional(
            summary.averageVerticalRatioPercent
        )
        averageStanceTimeBalancePercent = ExportMetricSanitizer.optional(
            summary.averageStanceTimeBalancePercent
        )
        averageStepLengthMeters = ExportMetricSanitizer.optional(
            summary.averageStepLengthMeters
        )
    }
}

public struct SplitExport: Codable, Sendable {
    public let splitIndex: Int
    public let startDistanceKm: Double
    public let endDistanceKm: Double
    public let distanceKm: Double
    public let elapsedDurationSeconds: Double
    public let activeDurationSeconds: Double
    public let movingDurationSeconds: Double
    public let stoppedDurationSeconds: Double
    public let movingPaceSecondsPerKilometer: Double
    public let activePaceSecondsPerKilometer: Double
    public let elapsedPaceSecondsPerKilometer: Double
    /// Additive compatibility aliases: duration is elapsed; pace is active.
    public let durationSeconds: Double
    public let paceSecondsPerKilometer: Double
    public let elevationGainMeters: Double?
    public let averageHeartRateBPM: Double?
    public let averagePowerWatts: Double?

    public init(split: RunSplit) {
        splitIndex = split.splitIndex
        startDistanceKm = ExportMetricSanitizer.nonNegative(split.startDistanceMeters) / 1000
        endDistanceKm = ExportMetricSanitizer.nonNegative(split.endDistanceMeters) / 1000
        distanceKm = ExportMetricSanitizer.nonNegative(split.distanceMeters) / 1000
        elapsedDurationSeconds = ExportMetricSanitizer.nonNegative(split.elapsedSeconds)
        activeDurationSeconds = ExportMetricSanitizer.nonNegative(split.activeSeconds)
        movingDurationSeconds = ExportMetricSanitizer.nonNegative(split.movingSeconds)
        stoppedDurationSeconds = ExportMetricSanitizer.nonNegative(split.stoppedSeconds)
        movingPaceSecondsPerKilometer = ExportMetricSanitizer.nonNegative(split.movingPaceSecondsPerKilometer)
        activePaceSecondsPerKilometer = ExportMetricSanitizer.nonNegative(split.paceSecondsPerKilometer)
        elapsedPaceSecondsPerKilometer = ExportMetricSanitizer.nonNegative(split.elapsedPaceSecondsPerKilometer)
        durationSeconds = elapsedDurationSeconds
        paceSecondsPerKilometer = activePaceSecondsPerKilometer
        elevationGainMeters = ExportMetricSanitizer.optional(split.elevationGainMeters)
        averageHeartRateBPM = ExportMetricSanitizer.optional(split.averageHeartRateBPM)
        averagePowerWatts = ExportMetricSanitizer.optional(split.averagePowerWatts)
    }
}

public struct SegmentExport: Codable, Sendable {
    public let type: String
    public let title: String
    public let description: String
    public let startDistanceKm: Double
    public let endDistanceKm: Double
    public let distanceKm: Double
    public let startElapsedSeconds: Double
    public let endElapsedSeconds: Double
    public let activeDurationSeconds: Double
    public let elapsedDurationSeconds: Double
    public let activePaceSecondsPerKilometer: Double?
    /// Additive compatibility aliases use active semantics.
    public let durationSeconds: Double
    public let paceSecondsPerKilometer: Double?
    /// Defines whether the corrected elevation value is signed change,
    /// threshold-confirmed ascent, or threshold-confirmed descent.
    public let elevationMetric: String?
    /// Value matching `elevationMetric`; ascent and descent are positive magnitudes.
    public let correctedElevationValueMeters: Double?
    /// Backward-compatible signed-change field. Descents remain negative here.
    public let elevationDeltaMeters: Double?
    public let averageHeartRateBPM: Double?
    public let averagePowerWatts: Double?

    public init(segment: SegmentHighlight) {
        type = segment.type.rawValue
        title = segment.title
        description = segment.subtitle
        startDistanceKm = ExportMetricSanitizer.nonNegative(segment.startDistanceMeters) / 1000
        endDistanceKm = ExportMetricSanitizer.nonNegative(segment.endDistanceMeters) / 1000
        distanceKm = ExportMetricSanitizer.nonNegative(segment.distanceMeters) / 1000
        startElapsedSeconds = ExportMetricSanitizer.nonNegative(segment.startElapsedSeconds)
        endElapsedSeconds = ExportMetricSanitizer.nonNegative(segment.endElapsedSeconds)
        activeDurationSeconds = ExportMetricSanitizer.nonNegative(segment.activeDurationSeconds)
        elapsedDurationSeconds = ExportMetricSanitizer.nonNegative(segment.elapsedDurationSeconds)
        activePaceSecondsPerKilometer = ExportMetricSanitizer.positiveOptional(segment.paceSecondsPerKilometer)
        durationSeconds = activeDurationSeconds
        paceSecondsPerKilometer = activePaceSecondsPerKilometer
        elevationMetric = Self.elevationMetric(for: segment)
        correctedElevationValueMeters = Self.correctedElevationValue(for: segment)
        elevationDeltaMeters = ExportMetricSanitizer.optional(segment.elevationDeltaMeters)
        averageHeartRateBPM = ExportMetricSanitizer.optional(segment.averageHeartRate)
        averagePowerWatts = ExportMetricSanitizer.optional(segment.averagePowerWatts)
    }

    private static func elevationMetric(for segment: SegmentHighlight) -> String? {
        guard segment.elevationDeltaMeters != nil else { return nil }
        switch segment.type {
        case .biggestClimb:
            return "corrected_ascent"
        case .biggestDescent:
            return "corrected_descent"
        case .fastest400m, .fastest1km, .slowest1km, .slowdown, .custom:
            return "corrected_signed_change"
        }
    }

    private static func correctedElevationValue(for segment: SegmentHighlight) -> Double? {
        guard let value = ExportMetricSanitizer.optional(segment.elevationDeltaMeters) else {
            return nil
        }
        switch segment.type {
        case .biggestClimb:
            return value >= 0 ? value : nil
        case .biggestDescent:
            return value <= 0 ? -value : nil
        case .fastest400m, .fastest1km, .slowest1km, .slowdown, .custom:
            return value
        }
    }
}

private enum ExportMetricSanitizer {
    static func nonNegative(_ value: Double) -> Double {
        value.isFinite ? max(0, value) : 0
    }

    static func optional(_ value: Double?) -> Double? {
        guard let value, value.isFinite else { return nil }
        return value
    }

    static func positiveOptional(_ value: Double?) -> Double? {
        guard let value, value.isFinite, value > 0 else { return nil }
        return value
    }
}
