import Foundation

/// JSON-serializable workout summary for export.
public struct WorkoutExportSummary: Codable, Sendable {
    public let appName: String
    public let exportVersion: String
    public let exportDate: Date
    public let privacyNote: String

    public let workoutTitle: String
    public let source: String
    public let startDate: Date?
    public let endDate: Date?
    public let routePointCount: Int

    public let totalDistanceMeters: Double
    public let totalDurationSeconds: Double
    public let averagePaceSecondsPerKilometer: Double
    public let averageSpeedMetersPerSecond: Double

    public let elevationGainMeters: Double
    public let elevationLossMeters: Double

    public let averageHeartRateBPM: Double?
    public let maxHeartRateBPM: Double?

    public let splits: [SplitExport]
    public let segments: [SegmentExport]

    public init(workout: RunWorkout, segments: [SegmentHighlight]) {
        self.appName = "RunPlay Studio"
        self.exportVersion = "1.0"
        self.exportDate = Date()
        self.privacyNote = "Local export generated by RunPlay Studio. No data was uploaded to any server."

        self.workoutTitle = workout.displayName
        self.source = workout.source.rawValue
        self.startDate = workout.metadata.startDate
        self.endDate = workout.metadata.endDate
        self.routePointCount = workout.routePoints.count

        self.totalDistanceMeters = workout.summary.totalDistanceMeters
        self.totalDurationSeconds = workout.summary.totalElapsedSeconds
        self.averagePaceSecondsPerKilometer = workout.summary.averagePaceSecondsPerKilometer
        self.averageSpeedMetersPerSecond = workout.summary.averageSpeedMetersPerSecond

        self.elevationGainMeters = workout.summary.elevationGainMeters
        self.elevationLossMeters = workout.summary.elevationLossMeters

        self.averageHeartRateBPM = workout.summary.averageHeartRateBPM
        self.maxHeartRateBPM = workout.summary.maxHeartRateBPM

        self.splits = workout.splits.map { SplitExport(split: $0) }
        self.segments = segments.map { SegmentExport(segment: $0) }
    }
}

/// Exportable split data.
public struct SplitExport: Codable, Sendable {
    public let splitIndex: Int
    public let startDistanceKm: Double
    public let endDistanceKm: Double
    public let distanceKm: Double
    public let durationSeconds: Double
    public let paceSecondsPerKilometer: Double
    public let elevationGainMeters: Double?
    public let averageHeartRateBPM: Double?

    public init(split: RunSplit) {
        self.splitIndex = split.splitIndex
        self.startDistanceKm = split.startDistanceMeters / 1000
        self.endDistanceKm = split.endDistanceMeters / 1000
        self.distanceKm = split.distanceMeters / 1000
        self.durationSeconds = split.elapsedSeconds
        self.paceSecondsPerKilometer = split.paceSecondsPerKilometer
        self.elevationGainMeters = split.elevationGainMeters
        self.averageHeartRateBPM = split.averageHeartRateBPM
    }
}

/// Exportable segment highlight data.
public struct SegmentExport: Codable, Sendable {
    public let type: String
    public let title: String
    public let description: String
    public let startDistanceKm: Double
    public let endDistanceKm: Double
    public let distanceKm: Double
    public let startElapsedSeconds: Double
    public let endElapsedSeconds: Double
    public let durationSeconds: Double
    public let paceSecondsPerKilometer: Double?
    public let elevationDeltaMeters: Double?
    public let averageHeartRateBPM: Double?

    public init(segment: SegmentHighlight) {
        self.type = segment.type.rawValue
        self.title = segment.title
        self.description = segment.subtitle
        self.startDistanceKm = segment.startDistanceMeters / 1000
        self.endDistanceKm = segment.endDistanceMeters / 1000
        self.distanceKm = segment.distanceMeters / 1000
        self.startElapsedSeconds = segment.startElapsedSeconds
        self.endElapsedSeconds = segment.endElapsedSeconds
        self.durationSeconds = segment.durationSeconds
        self.paceSecondsPerKilometer = segment.paceSecondsPerKilometer
        self.elevationDeltaMeters = segment.elevationDeltaMeters
        self.averageHeartRateBPM = segment.averageHeartRate
    }
}
