import Foundation

/// JSON-serializable workout summary with explicit clock semantics.
public struct WorkoutExportSummary: Codable, Sendable {
    public let appName: String
    public let exportVersion: String
    public let exportDate: Date
    public let privacyNote: String
    public let workoutTitle: String
    public let source: String
    public let startDate: Date?
    public let endDate: Date?
    public let routePointCount: Int

    public let totalDistanceMeters: Double
    public let totalElapsedSeconds: Double
    public let totalActiveSeconds: Double
    public let totalPausedSeconds: Double
    public let activePaceSecondsPerKilometer: Double
    public let elapsedPaceSecondsPerKilometer: Double
    public let activeAverageSpeedMetersPerSecond: Double
    public let elapsedAverageSpeedMetersPerSecond: Double

    /// Additive v1 compatibility aliases. Duration means elapsed; average pace
    /// and speed retain their active semantics.
    public let totalDurationSeconds: Double
    public let averagePaceSecondsPerKilometer: Double
    public let averageSpeedMetersPerSecond: Double

    public let elevationGainMeters: Double
    public let elevationLossMeters: Double
    public let averageHeartRateBPM: Double?
    public let maxHeartRateBPM: Double?
    public let splits: [SplitExport]
    public let segments: [SegmentExport]

    public init(workout: RunWorkout, segments: [SegmentHighlight]) {
        appName = "RunPlay Studio"
        exportVersion = "2.0"
        exportDate = Date()
        privacyNote = "Local export generated by RunPlay Studio. No data was uploaded to any server."
        workoutTitle = workout.displayName
        source = workout.source.rawValue
        startDate = workout.metadata.startDate
        endDate = workout.metadata.endDate
        routePointCount = workout.routePoints.count

        let summary = workout.summary
        totalDistanceMeters = ExportMetricSanitizer.nonNegative(summary.totalDistanceMeters)
        totalElapsedSeconds = ExportMetricSanitizer.nonNegative(summary.totalElapsedSeconds)
        totalActiveSeconds = ExportMetricSanitizer.nonNegative(summary.totalActiveSeconds)
        totalPausedSeconds = ExportMetricSanitizer.nonNegative(summary.totalPausedSeconds)
        activePaceSecondsPerKilometer = ExportMetricSanitizer.nonNegative(summary.averagePaceSecondsPerKilometer)
        elapsedPaceSecondsPerKilometer = ExportMetricSanitizer.nonNegative(summary.elapsedPaceSecondsPerKilometer)
        activeAverageSpeedMetersPerSecond = ExportMetricSanitizer.nonNegative(summary.averageSpeedMetersPerSecond)
        elapsedAverageSpeedMetersPerSecond = ExportMetricSanitizer.nonNegative(summary.elapsedAverageSpeedMetersPerSecond)
        totalDurationSeconds = totalElapsedSeconds
        averagePaceSecondsPerKilometer = activePaceSecondsPerKilometer
        averageSpeedMetersPerSecond = activeAverageSpeedMetersPerSecond
        elevationGainMeters = ExportMetricSanitizer.nonNegative(summary.elevationGainMeters)
        elevationLossMeters = ExportMetricSanitizer.nonNegative(summary.elevationLossMeters)
        averageHeartRateBPM = ExportMetricSanitizer.optional(summary.averageHeartRateBPM)
        maxHeartRateBPM = ExportMetricSanitizer.optional(summary.maxHeartRateBPM)
        splits = workout.splits.map(SplitExport.init)
        self.segments = segments.map(SegmentExport.init)
    }
}

public struct SplitExport: Codable, Sendable {
    public let splitIndex: Int
    public let startDistanceKm: Double
    public let endDistanceKm: Double
    public let distanceKm: Double
    public let elapsedDurationSeconds: Double
    public let activeDurationSeconds: Double
    public let activePaceSecondsPerKilometer: Double
    public let elapsedPaceSecondsPerKilometer: Double
    /// Additive compatibility aliases: duration is elapsed; pace is active.
    public let durationSeconds: Double
    public let paceSecondsPerKilometer: Double
    public let elevationGainMeters: Double?
    public let averageHeartRateBPM: Double?

    public init(split: RunSplit) {
        splitIndex = split.splitIndex
        startDistanceKm = ExportMetricSanitizer.nonNegative(split.startDistanceMeters) / 1000
        endDistanceKm = ExportMetricSanitizer.nonNegative(split.endDistanceMeters) / 1000
        distanceKm = ExportMetricSanitizer.nonNegative(split.distanceMeters) / 1000
        elapsedDurationSeconds = ExportMetricSanitizer.nonNegative(split.elapsedSeconds)
        activeDurationSeconds = ExportMetricSanitizer.nonNegative(split.activeSeconds)
        activePaceSecondsPerKilometer = ExportMetricSanitizer.nonNegative(split.paceSecondsPerKilometer)
        elapsedPaceSecondsPerKilometer = ExportMetricSanitizer.nonNegative(split.elapsedPaceSecondsPerKilometer)
        durationSeconds = elapsedDurationSeconds
        paceSecondsPerKilometer = activePaceSecondsPerKilometer
        elevationGainMeters = ExportMetricSanitizer.optional(split.elevationGainMeters)
        averageHeartRateBPM = ExportMetricSanitizer.optional(split.averageHeartRateBPM)
    }
}

public struct SegmentExport: Codable, Sendable {
    public let type: String
    public let title: String
    public let description: String
    public let startDistanceKm: Double
    public let endDistanceKm: Double
    public let distanceKm: Double
    public let startElapsedSeconds: Double
    public let endElapsedSeconds: Double
    public let activeDurationSeconds: Double
    public let elapsedDurationSeconds: Double
    public let activePaceSecondsPerKilometer: Double?
    /// Additive compatibility aliases use active semantics.
    public let durationSeconds: Double
    public let paceSecondsPerKilometer: Double?
    public let elevationDeltaMeters: Double?
    public let averageHeartRateBPM: Double?

    public init(segment: SegmentHighlight) {
        type = segment.type.rawValue
        title = segment.title
        description = segment.subtitle
        startDistanceKm = ExportMetricSanitizer.nonNegative(segment.startDistanceMeters) / 1000
        endDistanceKm = ExportMetricSanitizer.nonNegative(segment.endDistanceMeters) / 1000
        distanceKm = ExportMetricSanitizer.nonNegative(segment.distanceMeters) / 1000
        startElapsedSeconds = ExportMetricSanitizer.nonNegative(segment.startElapsedSeconds)
        endElapsedSeconds = ExportMetricSanitizer.nonNegative(segment.endElapsedSeconds)
        activeDurationSeconds = ExportMetricSanitizer.nonNegative(segment.activeDurationSeconds)
        elapsedDurationSeconds = ExportMetricSanitizer.nonNegative(segment.elapsedDurationSeconds)
        activePaceSecondsPerKilometer = ExportMetricSanitizer.positiveOptional(segment.paceSecondsPerKilometer)
        durationSeconds = activeDurationSeconds
        paceSecondsPerKilometer = activePaceSecondsPerKilometer
        elevationDeltaMeters = ExportMetricSanitizer.optional(segment.elevationDeltaMeters)
        averageHeartRateBPM = ExportMetricSanitizer.optional(segment.averageHeartRate)
    }
}

private enum ExportMetricSanitizer {
    static func nonNegative(_ value: Double) -> Double {
        value.isFinite ? max(0, value) : 0
    }

    static func optional(_ value: Double?) -> Double? {
        guard let value, value.isFinite else { return nil }
        return value
    }

    static func positiveOptional(_ value: Double?) -> Double? {
        guard let value, value.isFinite, value > 0 else { return nil }
        return value
    }
}
